### ISSUE TITLE
I want to separate the text editor from the editor menu.

### ISSUE THREAD

**Issue by jtaxiexpress** [the-airbender/quill_html_editor#1]
<img width="363" alt="スクリーンショット 2022-11-18 0 30 20" src="https://user-images.githubusercontent.com/86914073/202488302-f3f5ded5-c4c5-46ec-b6fe-0a19a1bf59c2.png">

I want to put the editor menu in the appbar.
However, currently when I call QuillHtmlEditor, it shows two sets of widgets.

**Comment by the-airbender** [comment]
Hi **jtaxiexpress**, 

I appreciate your feedback :) 
I am trying add support to customise the toolbar

- To Add/Remove styles from toolbar
- Toolbar postion
- Dynamic height of the editor based on text

Will release this features incrementally in the coming releases.

Thanks!

**Comment by jtaxiexpress** [comment]
Thanks , It is help us

**Comment by the-airbender** [comment]
Hi @jtaxiexpress ,
The toolbar is now separated from the editor, you can add it in AppBar too. 
Checkout the prerelease version [1.0.0-dev.3](https://pub.dev/packages/quill_html_editor/versions/1.0.0-dev.3)

**Comment by rakib205** [comment]
Hi there, Any updates about inserting image & videos and adding custom buttons?

**Comment by the-airbender** [comment]
Hi @rakib205,

I have just published a newer version [ver 2.0.0](https://pub.dev/packages/quill_html_editor) 
Which has the capability to add or remove toolbar buttons based on configuration. 
I will work on adding custom buttons to the toolbar in later releases. 

Thanks
