### ISSUE TITLE
Pasting text into the editor throws a javascript error, and prevents onchange from firing

### ISSUE THREAD

**Issue by mi1971** [the-airbender/quill_html_editor#10]
Hey @the-airbender ,

When I use copy/paste in the quill editor, the paste causes the following error to throw. This stops your onChange event from firing, so pasted changes are not saved.

`TypeError: Cannot read properties of null (reading 'index')
about:srcdoc 137:39                             <fn>
https://cdn.quilljs.com/1.3.6/quill.js 8598:27  emit
https://cdn.quilljs.com/1.3.6/quill.js 1893:99  emit
https://cdn.quilljs.com/1.3.6/quill.js 1624:36  modify
https://cdn.quilljs.com/1.3.6/quill.js 1513:21  updateContents
https://cdn.quilljs.com/1.3.6/quill.js 8922:22  <fn>`

**Comment by the-airbender** [comment]
Hi @mi1971 ,
This is bug is fixed and deployed. [2.0.2](https://pub.dev/packages/quill_html_editor/versions/2.0.2)
