### ISSUE TITLE
[FEATURE] Button to show the current and replace current HTML

### ISSUE THREAD

**Issue by lucasdidur** [the-airbender/quill_html_editor#104]
Button to show the content html

**Comment by the-airbender** [comment]
Hi @lucasdidur,

Could you please me with some more information? Please give an example to understand it better.

Thanks :)

**Comment by the-airbender** [comment]
Hello @lucasdidur,

I hope you're doing well! 👋

Thank you for bringing up the issue and sharing your concern. After investigating further, it seems that we currently don't have enough information to address the reported problem. However, I'm marking this issue as "Closed" for now. 

If you encounter this issue again or have more details to provide, please feel free to reopen the issue, and we'll be more than happy to take another look. Your feedback is valuable to us, and we want to ensure the best possible experience for all users.

In the meantime, if you have any other questions or need further assistance, don't hesitate to reach out. We're here to help!

Wishing you a great day ahead! 😊

Thanks :)
