### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kadirgulluoglu** [the-airbender/quill_html_editor#109]
**Describe the bug**
Very slow

**To Reproduce**
first open very slow

** Device **
 - Device: iPhone 14 pro
 - OS: 16.4

**Comment by the-airbender** [comment]
Hello @kadirgulluoglu,

The editor scripts will take a little time to load for the first time. Once the scripts is cached, it will load almost instantly.
While the editor is loading, we are showing a default `CircularProgessIndicator`. However, we can also customise it, please check the example code below.

```dart
QuillHtmlEditor(
   text: "<h1>Hello</h1>This is a quill html editor example 😊",
   controller: controller,
   loadingBuilder: (context) { // add the loader here
      return const Center(
         child: CircularProgressIndicator(
         strokeWidth: 0.4,
         ));
 }),
```
I hope this helps you out. If you still face any issues, please feel free to open the issue. 

Thanks :)

**Comment by kadirgulluoglu** [comment]
In this way, both hangs occur and the loading builder is not visible.
https://github.com/the-airbender/quill_html_editor/assets/62450370/814d0e6a-f59e-40bb-8e95-2122f3910b12


```dart
QuillHtmlEditor(
        text: widget.htmlContent ?? "",
        hintText: "Açıklama Ekle",
        controller: _controller,
        isEnabled: true,
        minHeight: 400,
        loadingBuilder: (context) {
          return const Center(
              child: CircularProgressIndicator(
            strokeWidth: 0.4,
          ));
        },
      ),
    );
```
