### ISSUE TITLE
 isEnabled: false, 

### ISSUE THREAD

**Issue by Codphobia** [the-airbender/quill_html_editor#119]
**Describe the bug**
[isEnabled] as the name suggests, is used to enable or disable the editor When it is set to false, the user cannot edit or type in the editor. i isEnabled :false but it's not disabling eidtor.

**Comment by the-airbender** [comment]
Hello @Codphobia ,

Thanks for reporting the bug. I am able to replicate it. Will release a fix soon.

Thanks :)

**Comment by RayanZaki** [comment]
any update on the fix?

**Comment by the-airbender** [comment]
Hello @RayanZaki @Codphobia 

I have deployed a new version 2.2.6 with this fix. Please check it out and feel free to share your feedback.

Thanks :)

**Comment by Codphobia** [comment]
Im using your editor and trying to adding some images but whenever i generate pdf it's taking half text idk why.
