### ISSUE TITLE
[BUG] Black box screen flicker on rendering QuillHtmlEditor widget

### ISSUE THREAD

**Issue by AvendoOT** [the-airbender/quill_html_editor#129]
**Describe the bug**
When QuillHtmlEditor widget is first created, it flickers for a second (black box) and then it is fine.

**To Reproduce**
Create QuillHtmlEditor widget and navigate to the page with it.

**Expected behavior**
It would be nice to not have a short black flicker when opening the screen.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S21 FE

**Flutter Doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.3, on Pop!_OS 22.04 LTS 6.2.6-76060206-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
[✓] Connected device (3 available)
[✓] Network resources

**Comment by the-airbender** [comment]
Hello @AvendoOT ,

Sorry for the delayed response. As the editor needs to load the scripts, it takes sometime which is usually in milliseconds to render. However, we also have a loadingbuilder, where we can add custom loading indicator while the editor is loading. 
Could you please help me with a sample code and also a screenshot if possible to assess the issue better?

Thanks :)

**Comment by the-airbender** [comment]
Hello @AvendoOT 

I am closing this issue for now. Please feel free to reopen if you still face any issues.

Thanks :)

**Comment by komakur** [comment]
The problem still persists. And it happens on a real device with dark theme. loadingBuilder doesn’t actually help.
The issue can be reproduced using code from examples.
