### ISSUE TITLE
Change text color editor

### ISSUE THREAD

**Issue by jstdk** [the-airbender/quill_html_editor#13]
It would be nice if we could set the color of the text inside the editor in order to support dark mode. I added an example of how it could work (second screenshot)

![2023-02-05T16:40:49,690130662+06:30](https://user-images.githubusercontent.com/115603308/216816710-128fa653-3133-4478-8b6f-a32dd9b8370d.png)
![2023-02-05T16:42:09,313597129+06:30](https://user-images.githubusercontent.com/115603308/216816727-b6a3d677-8e41-481e-9013-736a7c27663a.png)

Thanks for your consideration @the-airbender

**Comment by the-airbender** [comment]
Hi @jstdk 
Thanks for sharing the screenshot as a reference. Will add this in next release

**Comment by the-airbender** [comment]
Hi @jstdk,
I have deployed a new version 2.0.5, which has an option to add custom font color.

**Comment by jstdk** [comment]
Fantastic @the-airbender, fastest response ever
