### ISSUE TITLE
[BUG] await controller.setText(text);

### ISSUE THREAD

**Issue by bennyprasetia** [the-airbender/quill_html_editor#135]
**Describe the bug**
This is the log error  (It's like not supported dependency), the value that we set is from Quill also. how to fix this ? 
VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., A JavaScript exception occurred (WKErrorDomain:4:{WKJavaScriptExceptionLineNumber: Unsupported Type: 0, WKJavaScriptExceptionMessage: TypeError: undefined is not a function, NSLocalizedDescription: A JavaScript exception occurred, WKJavaScriptExceptionColumnNumber: Unsupported Type: 0}), null)
#0      WKWebViewHostApiImpl.evaluateJavaScriptForInstances (package:webview_flutter_wkwebview/src/web_kit/web_kit_api_impls.dart:1061:7)
<asynchronous suspension>
#1      WebKitWebViewController.runJavaScriptReturningResult (package:webview_flutter_wkwebview/src/webkit_webview_controller.dart:414:28)
<asynchronous suspension>
#2      WebViewXController.callJsMethod (package:quill_html_editor/src/widgets/webviewx/src/controller/impl/mobile.dart:124:20)
<asynchronous suspension>
#3      QuillHtmlEditorState._setHtmlTextToEditor (package:quill_html_editor/src/quill_editor_wrappe<…>

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Flutter Doctor**
Please run `flutter doctor` in the terminal and add the  log here.

**Additional context**

**Comment by the-airbender** [comment]
Hello @bennyprasetia,

Sorry for a delayed response. Could you please share more info about this bug, like the platform, flutter version, screenshots if possible, to help me understand the issue better?

Thanks :)
