### ISSUE TITLE
Can you add some examples for the custom buttons

### ISSUE THREAD

**Issue by MischaKr** [the-airbender/quill_html_editor#14]
My current task to solve is: 
I would like to add some Text at the cursor position when a custom button is pressed. 

I'm not sure if this is possible. 

By having some examples of for instance: 
Get the selected Text or output some text at the cursor this could help others with this question as well.

**Comment by the-airbender** [comment]
Hi @MischaKr 

Insert text method is currently in progress, will be deployed in this week.
Will also add examples for all methods. 

Thanks!

**Comment by MischaKr** [comment]
Awesome to read, keep up the good work !!

**Comment by the-airbender** [comment]
Hi @MischaKr,

Sorry for the late response. The `insertText` method already deployed last week. Please go through the example, I have added some buttons to setText, insertText and embed image, videos. 
Will keep this issue open until I add complete examples. 

Thanks!

**Comment by MischaKr** [comment]
Awesome !! Will test soon :)
