### ISSUE TITLE
CustomStyleButton

### ISSUE THREAD

**Issue by Praveencodenex** [the-airbender/quill_html_editor#141]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by the-airbender** [comment]
Hi @Praveencodenex ,
Could you please provide more information regarding this?

Thanks

**Comment by the-airbender** [comment]
Hello @Praveencodenex ,
I am closing this issue for now, as there is no update. Please feel free to reopen.
Thanks :)
