### ISSUE TITLE
[BUG] PlatformException Failed evaluating JavaScript in iOS

### ISSUE THREAD

**Issue by icodelifee** [the-airbender/quill_html_editor#142]
**Describe the bug**
Hi, when i try to change the color of the text in my template/html, i get this error. This error also occurs when i set html using controller.setText() and it fails to set the text, but for changing color, the color change works but it still throws this same error

`PlatformException (PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., Instance of 'NSErrorData', null))`

I am using this template to test : https://github.com/leemunroe/responsive-html-email-template/blob/master/email-inlined.html

This error is being thrown by the package webview_flutter_wkwebview 2.9.5
**To Reproduce**

**Comment by the-airbender** [comment]
Hello @icodelifee,

Could you please share more details to understand the issue better? Like the quill_html_editor version, device model, flutter version, etc. 
Also,  I notices that the package version you mentioned above is not from the latest version. In the latest version of the `quill_html_editor`, we are using  `webview_flutter_wkwebview`: ^3.7.2

Please provide the requested details and let me know if the package update resolves the issue. Please don't hesitate to reach out if you have any additional questions or concerns.

Thanks :)

**Comment by the-airbender** [comment]
Hello @icodelifee,

I am closing the issue for now, as there is no update. However, please feel free to reopen the issue if you still see any problems.

Thanks :)
