### ISSUE TITLE
Tables don't get displayed at all

### ISSUE THREAD

**Issue by kuyaC** [the-airbender/quill_html_editor#15]
<table> and all related tags don't do anything and the content disappears as regular text:

**Comment by the-airbender** [comment]
Hi @kuyaC 

Could you please add the code snippet and some more information about what kind of data are you dealing with?

Screenshots will also be helpful.

Thanks!

**Comment by the-airbender** [comment]
Hi @kuyaC,

Thank you for the detailed description. Will look into this.

**Comment by the-airbender** [comment]
Hi @kuyaC,

I have just deployed a new version [Ver 2.0.6-dev.03 ](https://pub.dev/packages/quill_html_editor/versions/2.0.6-dev.3) which has the capability to show, add, modify tables. 

Regarding the setText issue, I have made slight modifications and deployed it in the same release. 
Also,  `_controller.setText(text);` will not call the setState function, there should not be any interventions with the state. 

Please try the new pre-release version and share your feedback :)

Thanks!
