### ISSUE TITLE
[FEATURE] export EPUB file

### ISSUE THREAD

**Issue by EpicKim** [the-airbender/quill_html_editor#150]
Export file as xxx.EPUB

**Comment by the-airbender** [comment]
Hello @EpicKim,

Thank you for feature request. Could you please help me with more information on this? Please share some examples, sample code to understand it better.

Thanks :)

**Comment by the-airbender** [comment]
Hello @EpicKim,

I hope you are having a great time!
I am closing this issue as there is limited information regarding this at the moment. However, please feel free to reopen this. 

Thanks ;)
