### ISSUE TITLE
Support for Desktop

### ISSUE THREAD

**Issue by jogehl** [the-airbender/quill_html_editor#151]
Hello, 
is there the plan to expand the editor also for using on desktop platforms (Windows/MacOS/Linux)?

Best Regards!

**Comment by the-airbender** [comment]
Hello @jogehl ,

The functionality of quill_html_editor relies on the webview_flutter package, which currently offers support exclusively for Android, iOS, and Web platforms. I am open to extending the editor's compatibility to additional platforms, provided that webview support becomes available for those platforms. For now, I will close this issue; however, please feel free to reopen if needed.

Thanks :)

**Comment by Aruljebaraj** [comment]
any update on this?
