### ISSUE TITLE
[BUG] If show Dialog in front of HtmlEditor  but I can't touch the dialog

### ISSUE THREAD

**Issue by Palimoraihan** [the-airbender/quill_html_editor#158]
if I have show Dialog in front of HtmlEditor  
but I can't touch the dialog how i can fix

**Comment by the-airbender** [comment]
Hello @Palimoraihan 

Please check my comment in another issue here.
https://github.com/the-airbender/quill_html_editor/issues/83#issuecomment-1568726323

Hope this helps!

Thanks :)
