### ISSUE TITLE
[BUG] Insert link not showing in QuilHtmlEditor

### ISSUE THREAD

**Issue by bennyprasetia** [the-airbender/quill_html_editor#168]
**STEP 1 :**
![WhatsApp Image 2024-02-04 at 11 44 53](https://github.com/the-airbender/quill_html_editor/assets/11455725/5c7a7bbd-c332-4325-86ab-3dd208e077fd)
**STEP 2 :**
![WhatsApp Image 2024-02-04 at 11 45 07](https://github.com/the-airbender/quill_html_editor/assets/11455725/15562d05-f4c4-4647-9859-eec13b16f2dd)
**STEP 3 :**
![WhatsApp Image 2024-02-04 at 11 45 39](https://github.com/the-airbender/quill_html_editor/assets/11455725/2f31ee63-19bb-408b-9f9c-125887c53a47)

**Describe the bug**
When put the link, we are not able to see the link inside QuillHtmlEditor.
Is there any suggestion or you will fix this ?

**To Reproduce**
1. Please look at Step 1, 2 and 3

**Expected behavior**

**Screenshots**
Please look at Step 1, 2 and 3

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 11

**Flutter Doctor**
Please run `flutter doctor` in the terminal and add the  log here.

**Additional context**

**Comment by the-airbender** [comment]
Hello @bennyprasetia,

Thanks for reporting the issue.  I see that you have not selected any text to insert the hyperlink.  As per quilljs editor, the hyperlink can not be inserted without selecting a text. 

Please select the text and try to insert a hyperlink. I will enhance this behaviour in the future releases. 

Thanks :)
