### ISSUE TITLE
Callback to know if the editor is focus or not

### ISSUE THREAD

**Issue by Lyokone** [the-airbender/quill_html_editor#17]
Hello :) 

I would like to toggle the Toolbar when the user clicks on the `QuillHtmlEditor`.
Currently, the only way I see of getting the focus is using `controller.hasFocus`. I would like to have a callback directly on the QuillHtmlEditor or to listen to the controller state to change my UI depending on the editor's focus.

Thanks for your editor :)

**Comment by the-airbender** [comment]
Hi @Lyokone ,
Thank you for your feedback. That's a good suggestion, will add it in the coming release :)
Thanks!

**Comment by the-airbender** [comment]
Hi @Lyokone ,

I have added the `onFocusChanged` callback to listen to the focus change events of the editor in  the new version [v2.0.7](https://pub.dev/packages/quill_html_editor)

Thanks!
