### ISSUE TITLE
Ability to change hint text style

### ISSUE THREAD

**Issue by Lyokone** [the-airbender/quill_html_editor#18]
Currently, there is no way to change the default hint text style. I cannot change the font or make it not italic.
![IMG_5EC549DB457C-1](https://user-images.githubusercontent.com/3680002/218482676-6dc16325-1a9a-4c8d-bdaf-9106d03dffd5.jpeg)

**Comment by the-airbender** [comment]
Hi @Lyokone,
This is currently in progress, will be deployed in the coming release.

**Comment by the-airbender** [comment]
Hi @Lyokone,

With the new version [v2.0.7](https://pub.dev/packages/quill_html_editor), added the capability to customise HintText's `FontStyle` (bold, italic), `FontSize`, `FontWeight`, `TextAlignment` of **HintText** and also default editor text.
Adding **FontFamily** is in progress, will be tracked separately.

Thanks!
