### ISSUE TITLE
I would like the ability to embed youtube videos within the editor.

### ISSUE THREAD

**Issue by jtaxiexpress** [the-airbender/quill_html_editor#2]
If the user enters a URL, I want to display a youtube video within this editor.

**Comment by the-airbender** [comment]
Hi **jtaxiexpress**

That is a good suggestion. It will be added as part of toolbar customisation 
Closing this in favour to https://github.com/the-airbender/quill_html_editor/issues/1#issuecomment-1319640146 

I appreciate your feedback.
