### ISSUE TITLE
Unhandled Exception: LateInitializationError: Field '_webviewController@807047633' has not been initialized.

### ISSUE THREAD

**Issue by paraslamsong** [the-airbender/quill_html_editor#25]

**Comment by the-airbender** [comment]
Hi @paraslamsong,

Could you please share the following details to understand it better?

- Steps to reproduce the behavior
- Expected behavior
- Screenshots If applicable, please add screenshots to help explain your problem.
- Platforms: [e.g. iOS, Android, Web]
- Flutter and Dart SDK version
- Minimum Reproduceable Example Add a minimum reproduceable sample

Thanks!

**Comment by paraslamsong** [comment]
Problem on calling method setText using QuillEditorController:  controller.setText(body);
Platform: Android
Flutter 3.7.0
Expected behavior: Editor should populate with html data of body
 

<img width="971" alt="image" src="https://user-images.githubusercontent.com/87746599/219989443-218d3373-3e6d-46a6-be9b-7cb6109eb9b2.png">

**Comment by paraslamsong** [comment]
PS: Removing WidgetsBinding and  Adding delay of 1 second solved the problem

**Comment by the-airbender** [comment]
Hi @paraslamsong ,

Thanks for the detailed info. :-)

If you are trying to pass text as soon as the view is created, please use the  `text` parameter in `QuillHtmlEditor` widget, it will set the initial text to the editor as soon as the view is loaded. 
```dart
///Example: Passing initial text to the editor

QuillHtmlEditor(
    text: "Hello There!", // pass initial text here to load on created.
    hintText: 'Hint text goes here',
    controller: controller,
)
```
The reason for this behaviour is, the Webview has a few milliseconds delay in setting up and loading the editor, when we try to access the `controller` methods during this period, it is throwing an error. 

However, I am also going to add `editorCreated` callback to the `QuillHtmlEditor` widget,  to pass any initial data or set formats to the controller properly on editor initialised. 

Thanks!

**Comment by paraslamsong** [comment]
@the-airbender 
Thanks!

**Comment by bhargav-me** [comment]
@the-airbender - I am facing the same issue with v2.2.8

```
LateInitializationError: Field '_webviewController@953047633' has not been initialized.

When the exception was thrown, this was the stack: 
#0      QuillHtmlEditorState._webviewController (package:quill_html_editor/src/quill_editor_wrapper.dart)
#1      QuillHtmlEditorState.dispose (package:quill_html_editor/src/quill_editor_wrapper.dart:193:5)
#2      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5689:11)
#3      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:2076:13)
#4      ListIterable.forEach (dart:_internal/iterable.dart:49:13)
#5      _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:2085:25)
#6      BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2764:15)
#7      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3174:7)
```


**Platform:** iOS 17.5 Simulator

**SDK**
  dart: ">=3.3.2 <4.0.0"
  flutter: ">=3.19.2"


**Code:**
```
class CommentTextField extends StatelessWidget {
  final QuillEditorController _controller = QuillEditorController();

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      mainAxisSize: MainAxisSize.min,
      children: [
        QuillHtmlEditor(
          controller: _controller,
          minHeight: 50,
        ),
        Visibility(
          child: ToolBar(controller: _controller),
          visible: false,
        ),
      ],
    );
  }
}
```
