### ISSUE TITLE
Will support Windows platform?

### ISSUE THREAD

**Issue by cozyboy** [the-airbender/quill_html_editor#27]
Most of the editing work is still carried out on the PC. It would be great if it supports the windows platform.

**Comment by the-airbender** [comment]
Hi @cozyboy,

At the moment, the **webview_flutter** plugin only supports Android, iOS and web platforms.

I am very much excited to add support for other platforms. Will definitely add it once this following item is closed, as **quill_html_editor** relies up on this webview plugin.

Please refer to the open [issue](https://github.com/flutter/flutter/issues/99597#issuecomment-1060251147) in flutter repo.

Closing this issue for now, will comment here once the feature is available.

Thank you!
