### ISSUE TITLE
Pngs of Toolbar not working

### ISSUE THREAD

**Issue by prembankerquicko** [the-airbender/quill_html_editor#28]
Firstly, amazing job on the library. I have been looking for a quill editor which has support for flutter web. Integrating it was smooth as well. I, however ran into this issue. While integrating the default toolbar, it is looking for the PNG images of certain icons at a path where the images are not present and hence, it breaks the UI, here is a screenshot

![image](https://user-images.githubusercontent.com/84441067/220891573-5de75e53-e0d6-4aad-b6e0-9e7824ac1f1a.png)

Solution to this could be loading images over network instead of a local folder. Alternatively, giving functionality to add custom images/icon for buttons might help users override these icons themselves. 

Do let me know your thoughts on this. Thanks

**Comment by the-airbender** [comment]
Hi @prembankerquicko 

Thank you for you feedback. :)

This seems strange, the local assets are loading well on all three platforms for me. I would like to debug and fix this.
Could you please share few more details, to help me fix it?

1. Steps to reproduce the behavior
2. Expected behavior
3. Screenshots If applicable, please add screenshots to help explain your problem.
4. Platforms: [e.g. iOS, Android, Web]
5. Minimum Reproduceable Example Add a minimum reproduceable sample


Also, I have plans to make custom buttons having the capability to map to a style, which gives the users option to add custom icons for styles. 

**Example**:
```dart
ToolBar(
      toolBarColor: _toolbarColor,
      controller: controller,
      customButtons: [
        CustomButton( /// planning to add a custombutton widget, for now, we can add any widget there, refer example
             type:  ToolBarStyle.bold, /// Something similar to this
            onTap: () async {},
            child: const Icon(
              Icons.favorite,
              color: Colors.black,
            )),
         ]
);
```
Thanks!

**Comment by prembankerquicko** [comment]
Hi @the-airbender , 
thanks for the quick reply : D

1) To reproduce the steps, 

- Set up a flutter web app in your local and add your `quill_html_editor` as a dependency using pub.
- I copied over 'MyApp' widget present in main.dart inside lib of the example that you have provided and renamed it to 'CustomQuillEditor'.
- I injected this 'CustomQuillEditor' widget in my other widget for using it and then, the whole toolbar + editor is displayed and the missing PNGs issue is then observed.

Bug Screenshot: 
![image](https://user-images.githubusercontent.com/84441067/220908439-34392721-beb7-420b-b31c-d1395ecf5128.png)


Expected Behavior Screenshot:
![image](https://user-images.githubusercontent.com/84441067/220907894-be787b8b-3064-43e3-a8d9-2459937473f3.png)


2) Platform is Web


The issue is arising because `quill_html_editor` is importing images from the following local folder path (I am currently running
my app on localhost) where the PNGs are not actually present:
`http://127.0.0.1:4200/assets/packages/quill_html_editor/assets/insert_column_left.png`

Whereas for you on your website [https://the-airbender.github.io/#/](url), it is accessing the PNGs from your local assets folder which works because your dependancy seems to be injected locally. Here is your path URL.
`https://the-airbender.github.io/assets/packages/quill_html_editor/assets/camera_roll_icon.png`



A Quick Fix might be changing paths of PNGs in `image_constants.dart` to a hosted URL (might be the link above) and 
in your `tool_bar.dart` & `edit_table_drop_down.dart`, you can use `Image.network` instead of `Image.asset`


Do let me know if this seems like a viable problem and solution and let me know if I can help.

PS: The CustomButton functionality seems neat.

**Comment by the-airbender** [comment]
Hi @prembankerquicko,

Thanks for the detailed info.

I have followed the suggested steps, created a new flutter project, added `quill_html_edtior` in `pubspec.yaml` file. The asset images are loading fine for me. The assets should be bundled with the plugin.  

### If we run the web app, the assets will be visible in the build folder like shown below:

<img width="533" alt="image" src="https://user-images.githubusercontent.com/57312080/220976894-f1ece360-6ff9-4e96-99ea-7dfc2c1c889f.png">

### If we build the web app, the assets will be bundled as shown below:

<img width="533" alt="image" src="https://user-images.githubusercontent.com/57312080/220977312-702cec74-1f2a-4d02-8921-f06331b7dd41.png">

I have not added network images, as it might add additional dependency for the users, incase if the hosting goes down. 

Just to make sure, may I know if you run the `flutter clean` && `flutter pub get `commands to clear the old build files? If not, could you please try it out and let me know?


Thanks!

**Comment by prembankerquicko** [comment]
Hi @the-airbender ,
Thanks. 

Till now, I was testing on localhost and hence not built the app yet. I will build it asap and let you know if its working or no.

**Comment by the-airbender** [comment]
> Hi @the-airbender , Thanks.
> 
> Till now, I was testing on localhost and hence not built the app yet. I will build it asap and let you know if its working or no.

Hi @prembankerquicko,

Any update this issue? 

Thanks!

**Comment by prembankerquicko** [comment]
Hi @the-airbender ,

apologies for the delay. Yes as you said I was able to find the pngs in the assets
![image](https://user-images.githubusercontent.com/84441067/221809027-c77044ad-c4aa-45ee-81ae-09f334d03ce0.png)

Thanks for helping me out here. Closing this issue : )

**Comment by the-airbender** [comment]
I am glad, it is working :)

Thanks!
