### ISSUE TITLE
Inserting Images

### ISSUE THREAD

**Issue by mi1971** [the-airbender/quill_html_editor#3]
Hi, thank you for working on this. It is amazing to finally have a simple HTML editor. Can you tell me if it is possible to insert images?

**Comment by mi1971** [comment]
Fantastic – look forward to it

**Comment by the-airbender** [comment]
Hi @mi1971 ,
Checkout the prerelease version [1.0.0-dev.3](https://pub.dev/packages/quill_html_editor/versions/1.0.0-dev.3)
Added support for inserting images, embedding videos, hyperlinks.

**Comment by mi1971** [comment]
Hey, thank you. I'm having issues with the editor breaking sentences into multiple lines when there is an initial value passed to it that contains markup. See image below.

Also, the insert link button looks funny (textbox is tiny). I'm working on web.

I hope you can continue to work on this. It's so promising for flutter to have such a simple html editor.

<img width="325" alt="Screen Shot 2022-12-11 at 3 34 40 pm" src="https://user-images.githubusercontent.com/7830054/206888204-9835fe6b-af9e-4f51-8edc-2ac4a6d14be2.png">

**Comment by the-airbender** [comment]
Hi @mi1971 ,
Thanks for testing the beta version and reporting the issue. I have made a few bug fixes, which are not deployed yet. However this seems to be a new bug, will look into it.

**Comment by mi1971** [comment]
Thank you!!

**Comment by the-airbender** [comment]
Hi @mi1971 
Deployed a new beta version [1.0.0-dev.5](https://pub.dev/packages/quill_html_editor/versions/1.0.0-dev.5). Resolved the bugs you reported, along with a few other bugs.

**Comment by mi1971** [comment]
Thanks! line breaks look better. 

Your insert link dialog still looks wrong. Hint text should be same size (but lighter) than link text, and the text box should have some padding and be bigger. You've made the dialog bigger with what looks like a text box which is too big, but the real text box is still very skinny.

Here is yours versus one that looks good online....

<img width="422" alt="Screen Shot 2022-12-21 at 9 03 56 pm" src="https://user-images.githubusercontent.com/7830054/208878582-54e781e0-442d-4e4f-ba12-0bf3adfa04b9.png">

Example one...

<img width="431" alt="Screen Shot 2022-12-21 at 9 11 12 pm" src="https://user-images.githubusercontent.com/7830054/208879957-4307b2dd-bb50-48f3-92b3-a1268abb9444.png">

I hope this feedback is helpful? Thanks again.
