### ISSUE TITLE
Long-term support project?

### ISSUE THREAD

**Issue by Dorbmon** [the-airbender/quill_html_editor#30]
I'd like to integrate this library into our project, so would this project be supported for long term?

**Comment by the-airbender** [comment]
Hi @Dorbmon,

Yes, I have plans to support the package for long term. As I use this package myself for production apps :) 

I welcome any contributions to the project, it can be feedback,bug reports or PRs to make it better. 

Thanks!

**Comment by v1talii-dev** [comment]
> But QuillJS itself seems to be [dead](https://github.com/quilljs/quill/issues/3359). Is it reliable enough for long term?

I would not recommend using quill. it has significant memory leaks https://github.com/quilljs/quill/issues/3749, and it seems that support is no longer allocated time.

**Comment by evbo** [comment]
please put a warning at the very top of the readme: "This repository is currently inactive or extremely low activity".

I, perhaps like many, saw outdated information pointing me to quill. Invested weeks getting ramped up to use it, then discovered a few github issues hinting this project may be dead with significant WIP.

That was a hard loss to recover from, please do this for others like me.

**Comment by shivaramanaiyer** [comment]
@evbo I feel you. I have been using quill for a few months now and while it does most things, the majority of the time I find myself hacking a solution and that just doesn't feel right!
