### ISSUE TITLE
[FEATURE] Can we bundle the quill package into Flutter package?

### ISSUE THREAD

**Issue by gerken-tss** [the-airbender/quill_html_editor#33]
Hello. First of all: thanks a lot for creating the only rich text editor for Flutter that actually works with HTML input and output. Although this is "just" mostly a WebView component that renders the JS plugin, this is of incredible value!!

**The problem:**

Right now, the quill JS lib is being fetched via CDN by the following lines

```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/quill/2.0.0-dev.4/quill.snow.min.css" />
  <!-- Include the Quill library -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/quill/2.0.0-dev.4/quill.min.js"></script>
```

This creates several issues:

- Without internet connection, the package won't display anything
- Everytime the `QuillHtmlEditor` widget ist being rendered, it will cause network traffic (only about 80 kb, but still)
- During rendering, there is a short delay which would accumulate if there were several `QuillHtmlEditor`s being displayed on a page. This is actually not that unlikely if I used the editor to only display HTML exactly like the editor

Would it be possible to bundle the minified JS and CSS along with the package and inject it as an inline JS and CSS where now the external URL is being referenced?

**Comment by gerken-tss** [comment]
Thank you very much!

Even if it didn't, couldn't you load the asset from outside the WebView and then inject it as a string into the WebView, putting it as an inline `<script>` and `<style>` into the HTML file?

**Comment by the-airbender** [comment]
> @the-airbender Thank you very much!
> 
> Even if it didn't, couldn't you load the asset from outside the WebView and then inject it as a string into the WebView, putting it as an inline `<script>` and `<style>` into the HTML file?

I thought about this earlier but, the js file has very large text in it, so wanted to see if we can load and import the js directly into the html page from assets.

I will try the approach you are suggesting, before working on the other one :)

Thanks!

**Comment by the-airbender** [comment]
Hello @gerken-tss,

In the latest version 2.2.0, I have removed the CDN dependency. The JS and CSS files are bundled with the package. 
I appreciate your inputs in this. Please try it out and share your feedback.

Thanks :)
