### ISSUE TITLE
[BUG] Output of getText cuts off part of the string if it's too long

### ISSUE THREAD

**Issue by VoyagerClass** [the-airbender/quill_html_editor#37]
if you set the initial Text with a long html string and then proceed to call getText, the output always cuts off part of the string

1) set initial value with a long html string
2) Call getText to get the html string output
The expected output should be the full html string

platform: Android

**Comment by the-airbender** [comment]
Hi @VoyagerClass 

Thank you for reporting the bug.

Could you also please share the following info? 

- Min reproducible code
- Sample input text
- Flutter doctor
- Android version if possible

Thanks!

**Comment by VoyagerClass** [comment]
I found out that the print() function wasn't giving the full output on the debug console, my bad.

**Comment by the-airbender** [comment]
> I found out that the print() function wasn't giving the full output on the debug console, my bad.
> 
> 

No problem! Glad it is working :)

Thanks!
