### ISSUE TITLE
[BUG] Text print prints even when onTextChange is uncommented

### ISSUE THREAD

**Issue by jstdk** [the-airbender/quill_html_editor#39]
**Describe the bug**
Even when I uncomment the print onTextChanged, it still echo's in the dart debugger

**To Reproduce**
comment onTextChanged and look at the debugger on typing

**Expected behavior**
No echo

**Screenshots**
![2023-03-15T08:57:15,955392281+06:30](https://user-images.githubusercontent.com/115603308/225190178-25c13539-3e92-4fca-87d5-8be10a4eaf91.png)
![2023-03-15T08:58:32,740066750+06:30](https://user-images.githubusercontent.com/115603308/225190311-3c763ab6-0720-4847-a24f-0056e21bb7d9.png)
![2023-03-15T09:03:20,842339891+06:30](https://user-images.githubusercontent.com/115603308/225190318-ac3d8fae-1997-4635-b73d-9e6ebc47077c.png)

**Desktop (please complete the following information):**
- Arch Linux / Sway / Chromium

**Comment by the-airbender** [comment]
Hi @jstdk ,

Thanks for reporting this issue.
It is resolved now in ver [2.1.6 ](https://pub.dev/packages/quill_html_editor/versions/2.1.6)

Thanks :)
