### ISSUE TITLE
Access to 'editor current height' info [FEATURE] 

### ISSUE THREAD

**Issue by jstdk** [the-airbender/quill_html_editor#40]
**Is your feature request related to a problem? Please describe.**
In order to dynamically set the height of the html editor (and widgets surrounding them), it would be great to have access to the current height of the html text. I see that this info is available in the text variable, but I can't really access it. 
![2023-03-15T08:57:15,955392281+06:30](https://user-images.githubusercontent.com/115603308/225192329-f0b71ff4-467f-4b05-9463-6c83484a2cc2.png)

**Describe the solution you'd like**
I would like to use the text variable onTextChange, and then use setState to update the height of the widgets. Something like this. 

![2023-03-15T09:16:43,715820152+06:30](https://user-images.githubusercontent.com/115603308/225192350-0a673f81-2e94-4931-b5dd-ad213a557023.png)
![2023-03-15T09:16:31,476992969+06:30](https://user-images.githubusercontent.com/115603308/225192359-65ac0e83-fb61-41bd-b73a-57ab153aee44.png)

**Describe alternatives you've considered**
I have tried to split the current text variable to see if I can access the 'editor current height' portion, but I am unable to (maybe I am doing something wrong). 

**Additional context**
Thanks for considering.

**Comment by the-airbender** [comment]
Hi @jstdk ,

I have added a `onEditorResized` callback that returns the height of the editor. Please check it out in ver [2.1.6](https://pub.dev/packages/quill_html_editor/versions/2.1.6)

Thanks!

**Comment by jstdk** [comment]
Fantastic @the-airbender, thanks!
