### ISSUE TITLE
[BUG] Redo button shows errors & Missing iOS folder.

### ISSUE THREAD

**Issue by DarkMarksDoe** [the-airbender/quill_html_editor#41]
**Describe the bug**

**To Reproduce**
1. Open Example app inside package
2. Create iOS folder
3. Run app into a real device
4. Type redo button a couple of times

**Expected behavior**
No errors shown

**Error**
`[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Result of JavaScript execution returned a `null` value. Use `runJavascript` when expecting a null return value.
#0      WebKitWebViewController.runJavaScriptReturningResult (package:webview_flutter_wkwebview/src/webkit_webview_controller.dart:306:7)
<asynchronous suspension>
#1      WebViewXController.callJsMethod (package:quill_html_editor/src/widgets/webviewx/src/controller/impl/mobile.dart:124:20)
<asynchronous suspension>
#2      QuillHtmlEditorState._redo (package:quill_html_editor/src/quill_editor_wrapper.dart:366:12)
<asynchronous suspension>
#3      QuillEditorController.redo (package:quill_html_editor/src/quill_editor_wrapper.dart:1068:5)
<asynchronous suspension>
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Result of JavaScript execution returned a `null` value. Use `runJavascript` when expecting a null return value.
#0      WebKitWebViewController.runJavaScriptReturningResult (package:webview_flutter_wkwebview/src/webkit_webview_controller.dart:306:7)
<asynchronous suspension>
#1      WebViewXController.callJsMethod (package:quill_html_editor/src/widgets/webviewx/src/controller/impl/mobile.dart:124:20)
<asynchronous suspension>
#2      QuillHtmlEditorState._redo (package:quill_html_editor/src/quill_editor_wrapper.dart:366:12)
<asynchronous suspension>
#3      QuillEditorController.redo (package:quill_html_editor/src/quill_editor_wrapper.dart:1068:5)
<asynchronous suspension>
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Result of JavaScript execution returned a `null` value. Use `runJavascript` when expecting a null return value.
#0      WebKitWebViewController.runJavaScriptReturningResult (package:webview_flutter_wkwebview/src/webkit_webview_controller.dart:306:7)
<asynchronous suspension>
#1      WebViewXController.callJsMethod (package:quill_html_editor/src/widgets/webviewx/src/controller/impl/mobile.dart:124:20)
<asynchronous suspension>
#2      QuillHtmlEditorState._redo (package:quill_html_editor/src/quill_editor_wrapper.dart:366:12)
<asynchronous suspension>
#3      QuillEditorController.redo (package:quill_html_editor/src/quill_editor_wrapper.dart:1068:5)
<asynchronous suspension>
`

**Smartphone (please complete the following information):**
 - Device: iPhone 14 pro
 - OS: iOS16.3.1

**Flutter Doctor**
Please run `flutter doctor` in the terminal and add the  log here.

`[✓] Flutter (Channel stable, 3.7.7, on macOS 13.1 22C65 darwin-arm64, locale en-MX)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2022.3.2)
[✓] VS Code (version 1.74.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
`

**Additional context**
Missing ios folder

**Comment by the-airbender** [comment]
Hi @DarkMarksDoe ,

Thanks for reporting the issue, it is resolved now and deployed in the version [2.1.7](https://pub.dev/packages/quill_html_editor/versions/2.1.7)

There is no specific configuration that is required in iOS folder, hence, I didn't include it in the repo. Will check in the iOS folder in next commit.

Thanks :)
