### ISSUE TITLE
[FEATURE] Add Wrap Alignment inside Toolbar

### ISSUE THREAD

**Issue by DarkMarksDoe** [the-airbender/quill_html_editor#42]
By Default, when we have a row of actions, Wrap alignment is always in: `WrapAlignment.start,`
<img src="https://i.ibb.co/J3C4Vk7/IMG-1858.jpg" alt="With hardcoded Wrap Alignment" width="200"/>

By creating this parameter to be user editable gives the freedom to be dynamic with any design.
<img src="https://i.ibb.co/265YFGq/IMG-1859.jpg" alt="With custom Wrap Alignment" width="200"/>

**Comment by the-airbender** [comment]
Hi @DarkMarksDoe 

I have added all Wrap properties in the `ToolBar`, which allows more customisation of the toolbar. It is now available in the new version [2.1.7](https://pub.dev/packages/quill_html_editor/versions/2.1.7)

I appreciate your feedback

Thanks!
