### ISSUE TITLE
[FEATURE] Implement QuillEditorController.getDelta

### ISSUE THREAD

**Issue by Tameflame** [the-airbender/quill_html_editor#45]
**Is your feature request related to a problem? Please describe.**
The webview causes a little bit of lag, which is a problem for when I want it to be read-only. For example when one of multiple tab_bar views. 

I see that delta is the underlying data format for quill.js, so if this package could export it using the controller, that would make it compatible with other packages like flutter_quill, and I can use their non-webview solution for rendering quill deltas.

**Describe the solution you'd like**
implement getDelta method to QuillEditorController that would convert the html string to Delta format.

**Describe alternatives you've considered**
I tried finding a way on my own to convert html to delta but can't find anything.

**Comment by gerken-tss** [comment]
@Tameflame 
Regarding the (initial) lag, I guess when [this issue](https://github.com/the-airbender/quill_html_editor/issues/33) is resolved, the lag will be gone.
A general solution to work with the quill delta format would nice nice, though.

**Comment by the-airbender** [comment]
@Tameflame @gerken-tss,

Thank for your inputs.
I have added the methods `getDetla` and `setDelta`,  will be released in the next version.

Thanks :)

**Comment by Tameflame** [comment]
@the-airbender Wow thanks so much! I'm using this in a production app so I'm really grateful for your work! Please feel free to close issue whenever you feel like.

**Comment by the-airbender** [comment]
Hi @Tameflame,

Please check out the ver [2.1.8](https://pub.dev/packages/quill_html_editor/versions/2.1.8) for `setDelta` and `getDelta` methods. 

Please share your feedback

Thanks :)

**Comment by Tameflame** [comment]
@the-airbender 
Thanks so much! The solution is in production now! Amazing work, really appreciate it!
