### ISSUE TITLE
[BUG] Mobile Web - Clicking on toolbar icon does not toggle highlight color, and keyboard loses focus

### ISSUE THREAD

**Issue by Tameflame** [the-airbender/quill_html_editor#46]
**Describe the bug**
When using this package on mobile web. (i.e. flutter web site, accessed on mobile web). If I click on a toolbar icon, the icon doesn't immediately turn to the activecolor, I have to start typing and then it will toggle to the correct state.

Also, if I click on the toolbar icon, it will cause my keyboard to go away.

**To Reproduce**
1. Go to [demo website](https://the-airbender.github.io/#/) using Chrome or Safari on ios
2. Click on bold toolbar icon

**Expected behavior**
When a toolbar icon is clicked, it should immediately toggle active color.

https://user-images.githubusercontent.com/26692217/226185664-b2519cd0-83b4-4b4f-9f8f-78ae67442657.mp4

**Comment by the-airbender** [comment]
Hi @Tameflame ,

The active color toggle issue is fixed in v2.1.9. Please check it out and share the feedback. 

Thanks :)
