### ISSUE TITLE
[BUG] Black screen the first time the widget is rendered

### ISSUE THREAD

**Issue by DarkMarksDoe** [the-airbender/quill_html_editor#47]
**Describe the bug**
Every first time that you want to show `quill_html_editor` there's a black screen instead of editor, this visual bug is showed only the first time.

**To Reproduce**
1. Run example app
2. After the page is created, review the first frames of the widget.

**Expected behavior**
The widget should be shown as expected with no black colors.

**Screenshots**
<img src="https://i.ibb.co/KxRdbnN/ezgif-com-video-to-gif-2.gif" alt="With custom Wrap Alignment" width="350"/>

**Smartphone (please complete the following information):**
 - Device:  iPhone 14 pro
 - OS:  iOS16.3.1

**Flutter Doctor**
[✓] Flutter (Channel stable, 3.7.7, on macOS 13.1 22C65 darwin-arm64, locale en-MX) [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1) [✓] Xcode - develop for iOS and macOS (Xcode 14.2) [✓] Chrome - develop for the web [✓] Android Studio (version 2021.3) [✓] IntelliJ IDEA Community Edition (version 2022.3.2) [✓] VS Code (version 1.74.2) [✓] Connected device (3 available) [✓] HTTP Host Availability

**Comment by the-airbender** [comment]
Hi @DarkMarksDoe 

Thank you for reporting this bug.

There is a few milli seconds delay in rendering the view, as the scripts are loading from CDN. This issue will be resolved once, we bundle the scripts locally and load it. There is an [issue](https://github.com/the-airbender/quill_html_editor/issues/33) already open regarding the same.

I am closing this one, as we already have another one to track.

Thank you :)

**Comment by gerken-tss** [comment]
@DarkMarksDoe 

A workaround is to display the editor in a Stack widget. On top of the editor you display a loading indicator initially as long as the editor is building up. Once the `onEditorCreated` callback is fired, you hide the loading indicator.
