### ISSUE TITLE
[BUG] Duplicate GlobalKeys detected in widget tree. 

### ISSUE THREAD

**Issue by HasanAlqaisi** [the-airbender/quill_html_editor#48]
**Describe the bug**
I have a page with **QuillHtmlEditor** that can be navigated from multiple places, that means I can have this page opened multiple times in the stack.
The problem is when that happenes the following message will appear:

> The following GlobalKeys were specified multiple times in the widget tree. This will lead to parts of the widget tree being truncated unexpectedly, because the second time a key is seen, the previous instance is moved to the new location. The keys were:
> - [GlobalKey#8f02b]
>   [LabeledGlobalKey<**QuillHtmlEditorState**>#07cc0]

 and QuillHtmlEditor does not have a key property to fix this problem

**To Reproduce**
Steps to reproduce the behavior
Let's assume that page A has the QuillHtmlEditor
1. Navigate using **Navigator.of(context).push** from page A to B
2. Navigate using **Navigator.of(context).push** from page B to A
3. See the error

**Expected behavior**
Having key property in QuillHtmlEditor to fix this problem

**Smartphone (please complete the following information):**
 - Device: [e.g. Galaxy note 9]
 - OS: [e.g. android 10]

**Flutter Doctor**

> Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.3, on Linux Mint 21.1 5.15.0-67-generic, locale
    en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.76.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
• No issues found!

**Comment by the-airbender** [comment]
Hi @HasanAlqaisi,

Could you please share a sample code to understand this better?

The possible reason I see here is that the `controller` might be defined as a global variable, which is being passed to the new editor page on push ( using same controller for multiple widgets). We need to define the controller inside the page's class so that it will generate new controller for the new screen that is being created on push. 

Thanks :)

**Comment by HasanAlqaisi** [comment]
> Hi @HasanAlqaisi,
> 
> Could you please share a sample code to understand this better?
> 
> The possible reason I see here is that the `controller` might be defined as a global variable, which is being passed to the new editor page on push ( using same controller for multiple widgets). We need to define the controller inside the page's class so that it will generate new controller for the new screen that is being created on push.
> 
> Thanks :)

HI,
You are right. I am using riverpod and the controller provider is not being disposed since there are listeners for it.
So the same controller provided used for multiple widgets
Thanks for helping!

**Comment by the-airbender** [comment]
Glad it is resolved.
Thanks for confirming :)
