### ISSUE TITLE
[BUG] cursor won't go down.

### ISSUE THREAD

**Issue by Atom02** [the-airbender/quill_html_editor#49]
when you type on the editor on android and press enter the cursor wont go down.. unless you add space after a word then press enter the cursor will go down. 
example

wrote something[PRESSENTERHERE] <------ The cursor won't go down.

wrote something [PRESSENTERHERE] <-------- The cursor go down as excepted.

**Comment by the-airbender** [comment]
Hi @Atom02 ,

I tried recreating this issue on Android API 31, it is working fine on the device I tested. 
Could you please share some more information like, Android version, device model, flutter doctor details ?

Thanks :)

**Comment by the-airbender** [comment]
Hi @Atom02 ,

Kindly reopen the issue with more details.

Thanks :)
