### ISSUE TITLE
onChange Event

### ISSUE THREAD

**Issue by mi1971** [the-airbender/quill_html_editor#5]
Hey @the-airbender,

Sorry if this is a silly question, but I can't find any events that I can listen to, to let me know when the  html has changed. There's no onchange for the QuillHtmlEditor control, and there's no listeners on the controller. I couldn't see it in the examples either.

**Comment by the-airbender** [comment]
Hi @mi1971 

That's a very good question. The onChange event is possible, I have worked on it but didn't include in this versions yet. You'll see it in the next version. 

Thanks!

**Comment by the-airbender** [comment]
Hi @mi1971 ,

Please check out the new pre release for onChange event.

[v 2.0.0-beta.1](https://pub.dev/packages/quill_html_editor/versions/2.0.0-beta.1)

**Comment by mi1971** [comment]
Thank you!! I'll check it out.
