### ISSUE TITLE
[FEATURE] Horizontally Scrollable Toolbar Support

### ISSUE THREAD

**Issue by hurkanugur** [the-airbender/quill_html_editor#50]
I tried to force Toolbar to have only one line and all the elements in the Toolbar can be scrolled left and right direction in one line.

I tried something like this:
```dart
        SingleChildScrollView(
          physics: const AlwaysScrollableScrollPhysics(
            parent: BouncingScrollPhysics(),
          ),
          scrollDirection: Axis.horizontal,
          child: ToolBar(
            direction: Axis.horizontal,
            ........
```
It seems the toolbar has infinite width. 

That's why after scrolling a while, the Toolbar looks like an empty space.

I would really appreciate it if you could add this as a feature.😄 

Other than that, I really love your work❤️ . Keep it up!🔥

**Comment by the-airbender** [comment]
Hi @hurkanugur,

I have added the capability to customise Toolbar orientation. It is deployed in the ver 2.1.9

Use `ToolBar.scroll` to make toolbar scrollable vertically or horizontally.
```dart
ToolBar.scroll(
     toolBarColor: _toolbarColor,
      padding: const EdgeInsets.all(8),
      iconSize: 25,
      iconColor: _toolbarIconColor,
      activeIconColor: Colors.greenAccent.shade400,
      controller: controller,
      crossAxisAlignment: CrossAxisAlignment.center,
      direction: Axis.vertical
)
```
Use `ToolBar` to have the standard behaviour similar to `Wrap` widget.

Please check it out and share the feedback.

Thanks :)
