### ISSUE TITLE
[BUG] Toolbar Throws setState() called after dispose() Exception

### ISSUE THREAD

**Issue by hurkanugur** [the-airbender/quill_html_editor#52]
When I make the toolbar visible/invisible according to its focus on the quill editor,
sometimes it throws an exception like this:
```dart
════════ Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
setState() called after dispose(): ToolBarState#cadfb(lifecycle state: defunct, not mounted)
```

**THE EXCEPTION IS THROWN IN HERE:**
Source code: **tool_bar.dart**
method: **_getFontColorWidget**
function call: **setState()**

**SUGGESTION:**
I think making the widget mounted check before calling setState would solve the problem:
```dart
if (mounted) {
  setState(() {  });
}
```
Also, making the mounted check everywhere in the source codes (both quill toolbar and quill editor codes) could prevent unexpected setState issues in the future.

**HOW TO PRODUCE:**
1. Use the toolbar as bottomNavigationBar in Scaffold
2. if the quill editor is focused, make the toolbar visible. Otherwise, make the toolbar invisible.
3. After a few try later, you should see the exception

**DEVICES:** 
iPhone 14 Pro Max (iOS 16.2)
Android WXGA API 32

**FLUTTER DOCTOR:**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.0 22A380 darwin-arm64, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
[✓] VS Code (version 1.76.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

Thank you in advance!

**Comment by the-airbender** [comment]
Hi @hurkanugur 

Thank you for reporting the issue.

Could you please share a minimum reproducible code, to help me understand it better?

Thanks :)

**Comment by hurkanugur** [comment]
Hey,
Interestingly, I couldn't reproduce the bug in a dummy project.
I'm trying to figure out why.
If I could reproduce it again or find the reason, I'll share it with you, thanks. ^^

**Comment by the-airbender** [comment]
Hi @hurkanugur ,

Kindly reopen the issue once you are able to reproduce it.

Thanks :)
