### ISSUE TITLE
[BUG] Listening to text change on Android is not working

### ISSUE THREAD

**Issue by gerken-tss** [the-airbender/quill_html_editor#53]
**Describe the bug**
On Android, the `onTextChanged` event of the `QuillEditorController` is never triggered. Same goes for the `onTextChanged` property of the `QuillHtmlEditor` widget. This makes it unusable for me in production systems because on Android, the placeholder never goes away and I can not use the text that's being entered. Using the newest version (2.1.7) of `quill_html_editor`.

Minimum reproducible example:

```
class TestWidget extends StatefulWidget {
  @override
  State<TestWidget> createState() => _TestWidgetState();
}

class _TestWidgetState extends State<TestWidget> {
  late final QuillEditorController _textEditingController;

  @override
  void initState() {
    _textEditingController = QuillEditorController();
    _textEditingController.onTextChanged((String text) {
      print(text);
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return QuillHtmlEditor(
      controller: _textEditingController,
      minHeight: 1,
    );
  }
}
```

I was able to reproduce this on a physical Google Pixel 4a and an Android emulator. On iOS everything seems fine.

<img src="https://user-images.githubusercontent.com/84321030/228307331-6eae314e-10eb-45cb-a75b-2192bb40d789.jpg" width="300">

**Flutter Doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.3, on macOS 13.1 22C65 darwin-arm64, locale
    en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.3)
[✓] Connected device (5 available)
[✓] HTTP Host Availability
```

**Comment by the-airbender** [comment]
Hi @gerken-tss,

This issue is resolved and deployed in the ver 2.1.9.
Please check it out and share the feedback.

Thanks :)
