### ISSUE TITLE
[BUG] Multiple widgets used the same GlobalKey 

### ISSUE THREAD

**Issue by stefan-weinand** [the-airbender/quill_html_editor#55]
I simply put two editors in a scaffold and the error appears. For reproduction I created a skeleton of my app screen.

By the way, a lot of messages saying 'updateAcquireFence: Did not find frame.' appear in the terminal.

**To Reproduce**
```
import 'package:flutter/material.dart';
import '../screens/dashboard.dart';
import 'package:quill_html_editor/quill_html_editor.dart';

class Test extends StatefulWidget {
  const Test({Key? key}) : super(key: key);

  @override
  State<Test> createState() => _TestState();
}

class _TestState extends State<Test> {
  final _cNewComment = QuillEditorController(),
      _cDescription = QuillEditorController();

  @override
  void dispose() {
    _cNewComment.dispose();
    _cDescription.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView(
        children: [
          ElevatedButton(
            onPressed: () {
              Navigator.push(
                context,
                MaterialPageRoute(builder: (context) => Dashboard()),
              );
            },
            child: const Text('back'),
          ),
          ToolBar(
            controller: _cDescription,
          ),
          QuillHtmlEditor(
            controller: _cDescription,
            minHeight: 200,
          ),
          ToolBar(
            controller: _cNewComment,
          ),
          QuillHtmlEditor(
            controller: _cNewComment,
            minHeight: 200,
          ),
        ],
      ),
    );
  }
}
```

**Desktop:**
 - OS: iOS

**Smartphone:**
 - Device: MI 10T Lite
 - OS: Android 12

**Flutter Doctor**
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.2.1 22D68 darwin-arm64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.76.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by the-airbender** [comment]
Hi @stefan-weinand 

Thanks for reporting the issue.
It is resolved and deployed in the latest version [2.1.8](https://pub.dev/packages/quill_html_editor/versions/2.1.8)
Please check it out and share the feedback.

Thanks :)

**Comment by the-airbender** [comment]
Regarding:  'updateAcquireFence: Did not find frame.' 
Please refer to the comments from the below github issue. 
https://github.com/flutter/flutter/issues/104268#issuecomment-1134964433

Thanks!

**Comment by stefan-weinand** [comment]
Hi @the-airbender 

everything is fixed now, thank you very much for the quick solution!!!

👍
