### ISSUE TITLE
[BUG] Toolbar.color, Toolbar.size and Toolbar.background Properties Have Overflow Problem

### ISSUE THREAD

**Issue by hurkanugur** [the-airbender/quill_html_editor#57]
When the toolbar is set as the bottomNavigationBar of the scaffold, the Toolbar.color, Toolbar.size and Toolbar.background properties overflow the screen.

![Simulator Screen Shot - iPhone 14 Pro Max - 2023-04-03 at 20 24 49](https://user-images.githubusercontent.com/60323880/229583144-a417cd82-1bd8-46a7-a46f-03446e213ca2.png)

![Simulator Screen Shot - iPhone 14 Pro Max - 2023-04-03 at 20 24 25](https://user-images.githubusercontent.com/60323880/229583157-5611876a-42f3-490e-a10f-8de4ccc4dc5b.png)

![Simulator Screen Shot - iPhone 14 Pro Max - 2023-04-03 at 20 24 19](https://user-images.githubusercontent.com/60323880/229583168-4352bcef-21bd-4b5a-a2ba-f27eaa22e347.png)

**You can test it by using this code:**
```dart
import 'package:flutter/material.dart';
import 'package:quill_html_editor/quill_html_editor.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MaterialApp(debugShowCheckedModeBanner: false, home: MyApp()));
}

const Color quillWidgetsBackColor = Color.fromARGB(255, 122, 160, 194);
const Color buttonColors = Color.fromARGB(255, 40, 98, 150);
const double buttonHeights = 50;
const Color iconColors = Colors.white;
const TextStyle textStyle = TextStyle(color: Colors.white, fontSize: 18);

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final QuillEditorController controller = QuillEditorController();

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark(),
      themeMode: ThemeMode.light,
      home: Scaffold(
        resizeToAvoidBottomInset: true,
        bottomNavigationBar: AdvancedQuillToolbar(quillEditorController: controller),
        body: Container(
          padding: const EdgeInsets.all(20),
          height: MediaQuery.of(context).size.height,
          child: ListView(
            children: [
              AdvancedQuillEditor(quillEditorController: controller),
            ],
          ),
        ),
      ),
    );
  }
}

@immutable
class AdvancedQuillToolbar extends StatelessWidget {
  const AdvancedQuillToolbar({
    super.key,
    required this.quillEditorController,
  });

  final QuillEditorController quillEditorController;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: MediaQuery.of(context).viewInsets,
      child: ToolBar(
        controller: quillEditorController,
        padding: const EdgeInsets.all(5),
        toolBarColor: quillWidgetsBackColor,
        activeIconColor: iconColors,
        iconColor: iconColors,
        toolBarConfig: const [
          ToolBarStyle.color,
          ToolBarStyle.size,
          ToolBarStyle.background,
        ],
      ),
    );
  }
}

@immutable
class AdvancedQuillEditor extends StatelessWidget {
  const AdvancedQuillEditor({
    super.key,
    required this.quillEditorController,
  });

  final QuillEditorController quillEditorController;

  @override
  Widget build(BuildContext context) {
    return QuillHtmlEditor(
      controller: quillEditorController,
      backgroundColor: quillWidgetsBackColor,
      minHeight: 1,
      hintTextAlign: TextAlign.start,
      hintText: 'This is the hint text of the quill editor',
      textStyle: textStyle,
      hintTextStyle: textStyle,
      padding: const EdgeInsets.all(5),
      hintTextPadding: const EdgeInsets.all(5),
    );
  }
}

```

**Smartphone:**
 - iPhone 14 Pro Max (iOS 16.2)
 - Pixel 6 Pro (Android API 33)

**Flutter Doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.9, on macOS 13.0 22A380 darwin-arm64, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
[✓] VS Code (version 1.77.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by hurkanugur** [comment]
Not related to this topic but you did a great job with the fixes for the 2.1.8 ❤️ 👏  
Looking forward to seeing the next updates 🚀

**Comment by MischaKr** [comment]
I think I just doubled up this issue with my own issue. 

Perhaps my issue helps to clarify the problem :)

**Comment by the-airbender** [comment]
Hi @hurkanugur,

Please check out the new release ver 2.1.9. 
Kindly share your feedback.

Thanks :)

**Comment by hurkanugur** [comment]
This is insane! Thanks for the amazing work! 💯 🚀
