### ISSUE TITLE
Set default text direction&align

### ISSUE THREAD

**Issue by RomanIvn** [the-airbender/quill_html_editor#58]
Hi,
This editor is the only thing that truly works well for RTL languages in Flutter.
The only thing I'm missing is a way to set the text direction and alignment to RTL by default for implementing in RTL websites. Users should not select RTL each time they enter the editor.

Any tips on how/where to quickly set it? (I'll fork for now)

Thanks,
Roman

**Comment by RomanIvn** [comment]
Answering myself here:
                                    onEditorCreated: () {
                                      qctl.setFormat(format: 'direction', value: 'rtl');
                                      qctl.setFormat(format: 'align', value: 'right');
                                      setState0(() {});
                                    }),

**Comment by the-airbender** [comment]
Hi @RomanIvn,

Thanks for answering. Hoping this helps others too. :)

Thanks!
