### ISSUE TITLE
[Bug] Cursor hidden while writing

### ISSUE THREAD

**Issue by AhmedHeikal** [the-airbender/quill_html_editor#59]
The editor cursor is hidden when user makes new line multiple times .. and as a result it's causing user to keep scrollin as s\he writes in the editor.

If you can declare the focusNode as a parameter for the editor to track the status and ensure visiblity of the cursor.

Also if you may make a bool to ensure visibilty along with the focusNode would be cery helpful .. but if not focusNode used would be sufficient.

Thamk you so much  @the-airbender

**Comment by the-airbender** [comment]
Hello @AhmedHeikal ,

This issue is resolved in the new release. 
Please feel free to share your feedback.

Thanks :)
