### ISSUE TITLE
Adding custom toolbar button or editing default icons

### ISSUE THREAD

**Issue by rakib205** [the-airbender/quill_html_editor#6]
How can I add custom toolbar button and edit the default icons/buttons?

**Comment by rakib205** [comment]
Found that in the beta release but some important features are missing like:

1. Online Image Insert
2. Youtube video embedding and preview

Hope you will work on these.
Thanks

**Comment by the-airbender** [comment]
Hi @rakib205 

Yes, custom toolbar buttons is in beta. Regarding adding the online images and embedding YouTube videos, I will add them in upcoming releases once I find sometime.

**Comment by jstdk** [comment]
Most usable HTML editor for Flutter hands down. Custom icons will allow me to match the colors of the default icons to the custom icons in dark mode (buttons are black, custom buttons are white).

**Comment by the-airbender** [comment]
> Most usable HTML editor for Flutter hands down. Custom icons will allow me to match the colors of the default icons to the custom icons in dark mode (buttons are black, custom buttons are white).
> 
> Will the update also include a 'color' option inside QuillHtmlEditor or a default ToolBarStyle color option for the text inside the editor? Thanks in advance
> 
> ![2023-02-03T18:15:46,159303304+06:30](https://user-images.githubusercontent.com/115603308/216595710-1d4a25ee-5472-47e1-b7fc-93ec559364c3.png)

Hi @jstdk ,
Thank you for your feedback :)
I just deployed a new version 2.0.3, which includes the functionality to customise color and  size of the toolbar items. Please check it out.

**Comment by jstdk** [comment]
@the-airbender, incredible, thanks for your feedback and quick update.
