### ISSUE TITLE
[FEATURE] Single Scrollable row for the toolbar

### ISSUE THREAD

**Issue by AhmedHeikal** [the-airbender/quill_html_editor#60]
The toolbar takes much vertical space in the current implementation .. if you can please make a boolean to give the user the freedom to make it one line and scrollabel or as the current implemntation.

Thank you @the-airbender

**Comment by the-airbender** [comment]
Hi @AhmedHeikal,

Thank you for the feature request. 

I am planning to work on this feature. Since, we already have an issue open for the same, I am closing this one. Please refer the [issue ](https://github.com/the-airbender/quill_html_editor/issues/50)for update regarding the same.

Thanks :)
