### ISSUE TITLE
[BUG] onFocusChanged not triggered correctly

### ISSUE THREAD

**Issue by AhmedHeikal** [the-airbender/quill_html_editor#61]
`onFocusChanged` parameter in the Editor .. is not working correctly .. 
1) it's not triggered when the controller has focus (so when the editor first has focus this function is not triggere) 
2) Also when the controller loses focus (controller.unfocus() is called) it's triggered three times with the last one being true (false-> false -> true)

[Update]
it's triggered on the first Focus only -> so the callback -> true  

Maybe the second bug has something to do with the first  bug-> as the last callback when the editor loses focus is true -> the callback isn't triggered again when it's actually true 

Platform used: iOS 

Thank you

**Comment by the-airbender** [comment]
Hi @AhmedHeikal,

Thanks for reporting the bug. 

Since, we already have an open issue, I am closing this. Please check the [issue](https://github.com/the-airbender/quill_html_editor/issues/51) for any updates.

Thanks :)
