### ISSUE TITLE
ToolBarStyle.background,

### ISSUE THREAD

**Issue by MischaKr** [the-airbender/quill_html_editor#62]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Flutter Doctor**
Please run `flutter doctor` in the terminal and add the  log here.

**Additional context**

**Comment by the-airbender** [comment]
Hi @MischaKr,

I am assuming this is a duplicate of the issue you created #63
Closing this issue. 

Thanks :)

**Comment by MischaKr** [comment]
Yes this was a mistake, thanks for closing it.
