### ISSUE TITLE
customToolBarList: ToolBarStyle.background adds table items

### ISSUE THREAD

**Issue by MischaKr** [the-airbender/quill_html_editor#63]
When using: 
toolBarConfig: customToolBarList,

Having the following toolbarlist: 
final customToolBarList = [
    ToolBarStyle.bold,
    ToolBarStyle.italic,
    ToolBarStyle.align,
    ToolBarStyle.color,
    ToolBarStyle.background,
    ToolBarStyle.listBullet,
    ToolBarStyle.listOrdered,
    ToolBarStyle.clean,
  ];
  
Adding ToolBarStyle.background, 
Adds 3 items: Add table / Edit table and the intended: Text background selection. 

It should only add the background editing options.

**Comment by the-airbender** [comment]
Hi @MischaKr,

This issue is resolved and deployed in the ver 2.1.9. 

Thanks :)
