### ISSUE TITLE
[BUG] Could not load content for webpack://Quill/node_modules/quill-delta/dist/O

### ISSUE THREAD

**Issue by jstdk** [the-airbender/quill_html_editor#64]
**Describe the bug**
The dart debugger throws various 404s when using the package

**To Reproduce**
Implement the extension as per the default instructions and open the dart debugger on page load

**Expected behavior**
No 404s

**Screenshots**
![inframe](https://user-images.githubusercontent.com/115603308/231694048-19c651cc-d0d6-4038-a595-dc10053a7ee0.png)

**Desktop (please complete the following information):**
 - OS: Linux PopOS
 - Browser: Brave

**Additional context**
Package works fine, the mentioned 404s do not break the functionality

**Comment by the-airbender** [comment]
Hi @jstdk ,

This issue has been resolved. Please try the latest version 2.2.0 and share the feedback. Please feel free to reopen if you still see any issues.

Thanks :)

**Comment by jstdk** [comment]
Thanks @the-airbender!
