### ISSUE TITLE
[BUG] Getting error with multiple editor in same page for web

### ISSUE THREAD

**Issue by ashekelahe** [the-airbender/quill_html_editor#69]
When Im trying to use one quill editor for input and another editor with disable editing mode for viewing inputted data then I'm getting error in flutter web:

Error:

Assertion failed: org-dartlang-sdk:///lib/_engine/engine/canvaskit/embedded_views.dart:673:12
!_overlays.containsKey(viewId)
is not true

**Comment by ashekelahe** [comment]
Thank you for your response.

**Screenshots:**
https://drive.google.com/file/d/14h_5u9gxtS0L7pgeXYMlfQlMY1EH5dZm/view?usp=share_link

**Desktop:**
Macbook Pro M1 Pro

**Flutter Doctor:**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.11, on macOS 13.3.1 22E261 darwin-arm64, locale en-BD)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

**Additional context:**
I have a system where I have to input HTML richtext as input for messaging and then need to show them. I can input text with this library but can't show those text with this same QuillHtmlEditor with disable editing mode. I want to use this editor for editor and viewer both use because other flutter_html library can't view every content like table, code block etc. So I need your help please.

Thanks in advance

**Comment by ashekelahe** [comment]
@the-airbender 
Thank you for your response.

**Screenshots:**
https://drive.google.com/file/d/14h_5u9gxtS0L7pgeXYMlfQlMY1EH5dZm/view?usp=share_link

**Desktop:**
Macbook Pro M1 Pro

**Flutter Doctor:**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.11, on macOS 13.3.1 22E261 darwin-arm64, locale en-BD)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

**Additional context:**
I have a system where I have to input HTML richtext as input for messaging and then need to show them. I can input text with this library but can't show those text with this same QuillHtmlEditor with disable editing mode. I want to use this editor for editor and viewer both use because other flutter_html library can't view every content like table, code block etc. So I need your help please.

**_Thanks in advance_**

**Comment by the-airbender** [comment]
Hi @ashekelahe,

Thanks for the details.

I see that there is an open [issue](https://github.com/flutter/flutter/issues/124919) in flutter repo regarding the same. As per one of the comments there, the issue should not be there in later flutter versions of 3.7.11. 

I will also investigate it from my end.

Thanks :)

**Comment by ashekelahe** [comment]
@the-airbender 
Thanks for your response.

But the issue still exists in Flutter 3.7.11 and 3.7.12. I have tried on both versions.

Thanks

**Comment by ashekelahe** [comment]
@the-airbender 
Can you make a viewer for your editor please so that we can show HTML text those we have written in the HTML editor?

**Comment by the-airbender** [comment]
> @the-airbender Can you make a viewer for your editor please so that we can show HTML text those we have written in the HTML editor?

Yes, I have actually created a viewer too. Will try to publish it as well. 
Now that we are also supporting delta formats in the editor, I will publish a viewer which supports both HTML and delta.

Thanks!

**Comment by ashekelahe** [comment]
@the-airbender 
Thanks for your effor. I'm waiting such this kind of view because other HTML viewer can't show everything properly like codeblock, table etc. Also please make sure to make your viewer web supported and selectable text.

**Comment by the-airbender** [comment]
Hello @ashekelahe,

This [issue](https://github.com/flutter/flutter/issues/124919) has been resolved and should be working fine on a Flutter Stable channel 3.10.0.  Please try this out with the latest stable branch. 

Regarding the viewer, I am yet to deploy it once the thorough testing is done on all platforms. I will keep track of it separately as a Feature. 

Please feel free to reopen this issue if you still face any problems.

Thanks :)
