### ISSUE TITLE
Enhancement : Need method to replace the selected text

### ISSUE THREAD

**Issue by mi1971** [the-airbender/quill_html_editor#7]
Hi @the-airbender,

I am having 2 problems with getSelectionRange....

1. The return value is cast as dynamic but it returns a String of the range object, rather than a map, which is very difficult to parse, as you cannot even run json.decode on it due to not having quotation marks.
2. the index is returned from getSelectionRange is based on the visible text, but ignores any html, so you can't use it, because getText includes html.

For example: if I use getText() which returns <b>12345</b>, and then I select  the number 2 in the editor, and call getSelectionRange, it returns an index of 1. It should return an index of 4 (ie include the html). Otherwise there is no way of being able to control where you inject text.

What I'm trying to achieve is to have a button that inserts a merge field eg '[first_name]' where the cursor is. I'm using the dart replaceRange function, but it's replacing the wrong section of text because the index is out.

Does this make sense? Thanks! Matt

**Comment by the-airbender** [comment]
Hi @mi1971 ,

**getSelectionRange** of quilljs editor by default returns the length of the text without including the html tags length. I will see if there is any workaround for this and will create a new method if possible.

However, if you want to insert text at the selection, we can introduce an **insertText** method.  I am working on this method, will be added in the next release.
Thanks

**Comment by mi1971** [comment]
Oh yes, insertText would be even better.  If the cursor was at a single
point, then it should just insert there. However if the cursor was
selecting a range, then inserttext should give me a parameter to say what
the existing selected text was, and then replace the selection with what I
give it.

That way, I could make a button called [make heading], and when the user
selects 'world' in hello world, I can replace it with <h1>world</h1>. (as
an example)

**Comment by mi1971** [comment]
@the-airbender Also, I created an email sending form, and when I send to Gmail the images are hidden.

It appears that most emails don't allow base64 embedded images in the html. They need the image on a server and a link to the image.

[https://stackoverflow.com/questions/46783599/base64-encoded-image-is-not-showing-in-gmail](https://stackoverflow.com/questions/46783599/base64-encoded-image-is-not-showing-in-gmail)

I've made a button that uploads the image and appends it at the end of the editor using setText(), but I can't control where the image goes due to the issues above.

But ultimately, it would be good if the image button of yours would take a future (where we can upload ourselves where we want) where we pass you back the link and then you can insert it into the doc? What do you think?

**Comment by the-airbender** [comment]
@mi1971,
based on our discussion here, below are the features we could add in coming releases. 

1. InsertText
2. replace selected text 
3. add an option to make future calls to upload images and set the url 

Thanks

**Comment by mi1971** [comment]
Thank you – I think you could combine number one and two depending on if there is a selected range or not.

Matt Ireland
0413 9999 51

**Comment by the-airbender** [comment]
@mi1971 , **getSelectionRange** method now returns SelectionModel object instead of dynamic. Moved in the **ver 2.0.2**

**Comment by mi1971** [comment]
Hey @the-airbender, thanks for all the recent changes. It's looking a lot better. Look forward to future improvements.

**Comment by the-airbender** [comment]
Hey @mi1971 ,

Just deployed a new version[ ver 2.0.6-dev.3](https://pub.dev/packages/quill_html_editor/versions/2.0.6-dev.3). Which has the `insertText` feature, I have added sample code for insertText in example, please check it out.

Thanks!

**Comment by the-airbender** [comment]
Hi @mi1971 ,

Added methods to `getSelectedText`, `replaceText` to replace selected text in the ver 2.0.9.
Adding _format_ to replaced text will be coming in next release.

Thanks!
