### ISSUE TITLE
[BUG] onFocusChanged does not work when the keyboard keeps staying active

### ISSUE THREAD

**Issue by hurkanugur** [the-airbender/quill_html_editor#71]
onFocusChanged only works when:
1) The keyboard changes state from invisible to visible
2) The keyboard changes state from visible to invisible

However, it does not work when the keyboard keeps staying active and focusing on other widgets (such as TextField).
Because onFocusChanged depends on the visibility changes of the keyboard.

**To Reproduce:**
1) Click on a text field (onFocusChanged is triggered because the keyboard visibility is changed from invisible to visible)
2) Click on the html editor (onFocusChanged is **not triggered** because the keyboard visibility is not changed (it is still visible))
3) Click back to the text field (onFocusChanged is **not triggered** because the keyboard visibility is not changed (it is still visible))
4) Press the back button of the device so that the keyboard disappears (onFocusChanged is triggered because the keyboard visibility is changed from visible to invisible)

**Smartphone:**
Android: Pixel 6 Pro API 33

**Flutter Doctor:**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [Version 10.0.17763.4252], locale tr-TR)
This is taking an unexpectedly long time...[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.11)
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.70.0)
[√] Connected device (4 available)
[√] HTTP Host Availability

• No issues found!

**Comment by the-airbender** [comment]
Hi @hurkanugur,
I have fixed this issue, deployed it in the ver 2.2.0. Please try it out and share the feedback. 
Thanks :)
