### ISSUE TITLE
[FEATURE] Add a `ToolBarStyle` for making gaps between buttons sets

### ISSUE THREAD

**Issue by bambinoua** [the-airbender/quill_html_editor#76]
It would be good to have a `ToolBarSlye` (eg. `ToolBarStyle.separator`) to use it as a separator of toolbar button sections for clarity.

![изображение](https://github.com/the-airbender/quill_html_editor/assets/45417992/bf72f700-ccc2-4c68-81b7-7dfe18b051b5)

**Comment by the-airbender** [comment]
Hello @bambinoua,

I have added the new toolbar style `ToolBarStyle.separator` in the latest version 2.2.0. Please try it out and share your feedback.

Thanks :)
