### ISSUE TITLE
[BUG] Double vertical scrollbar in flutter web

### ISSUE THREAD

**Issue by bambinoua** [the-airbender/quill_html_editor#77]
![изображение](https://github.com/the-airbender/quill_html_editor/assets/45417992/cfd8f3f2-f8f0-4f20-a0e0-9027fa190f5e)

**Comment by tiennv597** [comment]
I fixed it temporarily by removing  「overflow-y」

**Comment by the-airbender** [comment]
Hi @bambinoua , @tiennv597 ,

Sorry for late response, I was a little busy past weeks. Will fix it and release a new build, this weekend. 

Thanks!

**Comment by vedantmittal** [comment]
When can we expect the new release with fixed bugs?

**Comment by the-airbender** [comment]
Hello @vedantmittal,

I was a little busy last few weeks, has fixed this and several other bugs, currently testing the changes, will keep you posted once the release is out.

Thanks :)

**Comment by vedantmittal** [comment]
Hi Pavan(The-Airbender/Quill_html_editor),

Can you please confirm when you will update the package, my project is
stuck because we have some dependencies on your package and issues aren't
resolved yet.

**Comment by the-airbender** [comment]
Hello @vedantmittal, @bambinoua,

Please try the latest version 2.2.0 and feel free to share your feedback. This issue is only reproducible in Windows, as I have been working on Mac, it took some time to verify it on another windows machine.  
If you still see any issues, please open an issue.

Thanks :)

**Comment by vedantmittal** [comment]
It worked.
Thank you so much for your quick responses and support.

Regards
