### ISSUE TITLE
Control over padding and font

### ISSUE THREAD

**Issue by mi1971** [the-airbender/quill_html_editor#8]
Hey @the-airbender 

Just a feature request that will be easy when you have time...being able to control padding and textstyle in the editor.

You can see when I put it in my form, it doesn't match my other fields very well. The padding is way bigger, and font is smaller than my other form fields... Thank you!!

<img width="301" alt="image" src="https://user-images.githubusercontent.com/7830054/212498861-07f9c727-f0ac-470c-b0e2-821d2f8b0402.png">

**Comment by the-airbender** [comment]
Hi @mi1971 ,
That's a good suggestion, will add it in next release :)

**Comment by mi1971** [comment]
Thank you! Your quick responses have been very helpful.

**Comment by the-airbender** [comment]
Hi @mi1971 ,
The new version 2.0.3 has the capability to add custom padding and font size.  Adding custom font styles will be coming in future releases.

**Comment by mi1971** [comment]
Thank you!
