### ISSUE TITLE
[BUG] Problematic cursor when inserting new lines (Android)

### ISSUE THREAD

**Issue by gerken-tss** [the-airbender/quill_html_editor#85]
**Describe the bug**
On some Android devices including the simulator, the cursor behaviour when inserting new lines in the quill text editor is undesirable. In fact, the new line character is inserted, but the cursor does not move behind this newly inserted character.

**To Reproduce**
I was able to reproduce this behaviour on several physical devices like the Pixel 4a with Android 13.
It is also reproducible in the emulator. In my case, I used this configuration:

<img width="506" alt="image" src="https://github.com/the-airbender/quill_html_editor/assets/84321030/e7c699f2-e76e-482a-985b-fe4d93912dcb">

App wise I did nothing special:

```dart
QuillHtmlEditor(
  controller: QuillEditorController(),
  minHeight: 1,
  hintTextStyle: const TextStyle(
    fontStyle: FontStyle.normal,
    fontSize: 16,
    color: Colors.black45,
  ),
  textStyle: const TextStyle(
    fontStyle: FontStyle.normal,
    fontSize: 16,
    color: Colors.black87,
  ),
);
```

**Expected behavior**
After having inserted a new line character, the cursor is supposed to jump right behind it.

**Screenshots / Videos**

https://github.com/the-airbender/quill_html_editor/assets/84321030/b69a2735-db8a-423d-bb5c-06e15bb81008

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 13.1 (Ventura)

**Smartphone (please complete the following information):**
 - Device: Android devices like Pixel 4a or Emulator
 - OS: Android
 - Version: 13

**Flutter Doctor**
```
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.1 22C65 darwin-arm64, locale
    en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
```

**Comment by the-airbender** [comment]
Hi @gerken-tss ,
Sorry for the late response. 
I recommend you to create the `QuillEditorController` object outside the build method, for example:

``` dart
final QuillEditorController controller = QuillEditorController();

@override
Widget build(BuildContext context) {
  return QuillHtmlEditor(
    controller: controller,   /// passing the controller
    minHeight: 1,
    hintTextStyle: const TextStyle(
      fontStyle: FontStyle.normal,
      fontSize: 16,
      color: Colors.black45,
    ),
    textStyle: const TextStyle(
      fontStyle: FontStyle.normal,
      fontSize: 16,
      color: Colors.black87,
    ),
  );
}


```

Reason being, whenever we create an object of `QuillEditorController` it will create a new instance of GlobalKeys of Editor State and Streams. 

In the above example, you are passing the Controller directly in the build function, so whenever the keyboard is opened or closed, the build function will be triggered and creates a new instance of the controller.

This is what I believe is happening in your case.  Could you please try the above example and see if you still face the isssue?

Thanks :)
Pavan

**Comment by gerken-tss** [comment]
@the-airbender 
Hey! Thank you for the response.
I'm afraid this is not the reason. The example I provided was just simplified to:
* Make it easier for you to understand
* Isolate the issue by omitting the side-effects

In the real-world example, I intialize the controller like this:

```dart
  @override
  void initState() {
    _textEditingController = QuillEditorController();
    super.initState();
  }
```

and then later in the `build()` method use it like this:

```dart
QuillHtmlEditor(
  controller: _textEditingController,
  …
)
```

**Comment by the-airbender** [comment]
Hi @gerken-tss ,

Thank you for the detailed info.  I am able to recreate this issue. 
It seems to be an issue with the google **Gboard** keyboard, please refer to this [thread](https://issuetracker.google.com/issues/177757645). They have resolved the issue, but I guess it is not rolled out yet.  
Hoping this will be deployed soon. 

Thanks!

**Comment by gerken-tss** [comment]
@the-airbender 
Thank you for you research! :) 
I hope this issue will be resolved soon!

Kind regards!

**Comment by the-airbender** [comment]
Hi @gerken-tss ,

Since this issue is not in our control, I am closing this. If I see any new updates regarding this fix from google, I will post a comment here.
Feel free to reopen or post your comments here.

Thanks :)
