### ISSUE TITLE
Visible scrollable area in editor is truncated about 100 pixels from the bottom of the Widget

### ISSUE THREAD

**Issue by mi1971** [the-airbender/quill_html_editor#9]
Hey @the-airbender ,

The editor allows you to set a height, but the scrollable and visible area of the editor is about 100 pixels less, so there is a blank bar along the bottom of the editor.

This is more obvious if you wrap a container with a border around the editor, but see the following screenshot to explain.

<img width="467" alt="image" src="https://user-images.githubusercontent.com/7830054/212584375-a8a4ee16-b5cc-4638-a048-9975d586e790.png">

Let me know if this is the same on your end?

**Comment by mi1971** [comment]
Actually it looks like the problem only occurs after you click the focus into the editor....see below

![Kapture 2023-01-16 at 13 01 55](https://user-images.githubusercontent.com/7830054/212590372-d07861e4-1ed2-44b0-8da7-461ce46ddc53.gif)

**Comment by the-airbender** [comment]
Hi @mi1971  
Thanks for reporting, will check it out. Are you facing this issue on a mobile app or web app?

**Comment by mi1971** [comment]
I’m on web app. Thank you!

Matt Ireland
0413 9999 51

**Comment by the-airbender** [comment]
Hi @mi1971 
This bug is fixed and deployed. [2.0.2](https://pub.dev/packages/quill_html_editor/versions/2.0.2)
