### ISSUE TITLE
[FEATURE] Any chance to implement to desktop?

### ISSUE THREAD

**Issue by rodolfogoulart** [the-airbender/quill_html_editor#93]
There is any chance to implement to desktop?

**Comment by the-airbender** [comment]
Hi @rodolfogoulart,

At the moment, the webview_flutter plugin only supports Android, iOS and web platforms.

I am very much excited to add support for other platforms. Will definitely add it once this following item is closed, as quill_html_editor relies up on this webview plugin.

Please refer to the open https://github.com/flutter/flutter/issues/99597#issuecomment-1060251147 in flutter repo.

Closing this issue for now, will comment here once the feature is available.

Thank you!
