### ISSUE TITLE
[Bug] HTML content does not render

### ISSUE THREAD

**Issue by VishaliOSRapidops** [the-airbender/quill_html_editor#95]
**Describe the bug**
Html content does not render.

**To Reproduce**
1. Go to https://the-airbender.github.io/#/
2. Add this text `<p> </p><title>Life Style News Letter - Times of India</title><style type="text/css"> @media screen and (max-width:767px) { table[class="zm"] { width: 100% !important; } .kr { height: 20px!important; } table { width: 98% !important; margin: 0 auto; } } </style><!--###Heart attack risk rises on Mondays: Study###--><table align="center" border="0" cellpadding="0" cellspacing="0" class="zm" style="background-color:#FFF; font:11px Arial; color:#000;" width="650"><tbody><tr><td align="right"><a href="https://timesofindia.indiatimes.com/life-style" style="color:#d32000; text-decoration:none; font-weight:bold; padding:12px 5px; display:block;" target="_blank">Visit Website &gt;</a></td></tr><tr><td valign="top" width="650"><table border="0" cellpadding="0" cellspacing="0" width="650"><tbody><tr><td bgcolor="white" height="70"><table border="0" cellpadding="0" cellspacing="0" width="650"><tbody><tr><td align="left" height="70" valign="top" width="650"><img width="100%" alt src="http://timesofindia.indiatimes.com/photo/66710310.cms" style="max-width: 100%;"></td></tr></tbody></table></td></tr><tr><td bgcolor="white" height="20"><img width="10" height="20" align="top" src="http://timesofindia.indiatimes.com/photo/14690948.cms" style="max-width: 100%;"></td></tr><tr><td><table align="center" border="0" cellpadding="0" cellspacing="0" class="mx" width="650"><tbody><tr><td style="font:bold 32px/65px &apos;Georgia&apos;;">Today&apos;s Highlights </td></tr><tr><td><a href="http://timesofindia.indiatimes.com/newsletter/clicked/?cid=4558eb8b0b7c71cdc5da8b7d1f163656&amp;emailId=mitesh.salesmate@gmail.com&amp;url=https://timesofindia.indiatimes.com/life-style/health-fitness/health-news/heart-attack-study-says-mondays-can-give-you-more-serious-heart-attacks/photostory/100756659.cms?utm_source=newsletter&amp;utm_medium=email&amp;utm_campaign=Life_Style" style="color:#333; text-decoration:none;"><img height="315" width="610" style="max-width: 100%; border-radius: 7px;" src="http://timesofindia.indiatimes.com/thumb/msid-100756659,width-610,height-315.cms"></a></td></tr><tr><td style="font:bold 20px/40px Arial;"><a href="http://timesofindia.indiatimes.com/newsletter/clicked/?cid=4558eb8b0b7c71cdc5da8b7d1f163656&amp;emailId=mitesh.salesmate@gmail.com&amp;url=https://timesofindia.indiatimes.com/life-style/health-fitness/health-news/heart-attack-study-says-mondays-can-give-you-more-serious-heart-attacks/photostory/100756659.cms?utm_source=newsletter&amp;utm_medium=email&amp;utm_campaign=Life_Style" style="color:#333; text-decoration:none;">Heart attack risk rises on Mondays: Study</a></td></tr><tr><td style="font:normal 17px/25px Arial; color:#333;"><span style="display:block; height:50px; font:normal 17px/25px Arial; color:#333; overflow:hidden;">As per a new research, people are more likely to experience serious heart attacks on Monday than on...</span></td></tr><tr><td bgcolor="white" height="20"><img width="10" height="10" align="top" src="http://timesofindia.indiatimes.com/photo/14690948.cms" style="max-width: 100%;"></td></tr><tr><td bgcolor="white" valign="top"><table border="0" cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td class="kr" height="30"></td></tr><tr><td height="155" valign="top" width="206"><a href="http://timesofindia.indiatimes.com/newsletter/clicked/?cid=4558eb8b0b7c71cdc5da8b7d1f163656&amp;emailId=mitesh.salesmate@gmail.com&amp;url=https://timesofindia.indiatimes.com/life-style/fashion/web-stories/sharmila-tagore-to-jaya-bachchan-what-these-yesteryear-actors-wore-for-their-wedding/photostory/100746642.cms?utm_source=newsletter&amp;utm_medium=email&amp;utm_campaign=Life_Style"><img height="155" width="206" style="max-width: 100%; border-radius: 7px;" src="http://timesofindia.indiatimes.com/photo/100746642.cms"></a></td><td width="24"></td><td valign="top" width="380"><table border="0" cellpadding="0" cellspacing="0" width="380"><tbody><tr><td><span style="display:block; height:48px; font:bold 18px/25px Arial; text-transform:uppercase; overflow:hidden;"><a href="http://timesofindia.indiatimes.com/newsletter/clicked/?cid=4558eb8b0b7c71cdc5da8b7d1f163656&amp;emailId=mitesh.salesmate@gmail.com&amp;url=https://timesofindia.indiatimes.com/life-style/fashion/web-stories/sharmila-tagore-to-jaya-bachchan-what-these-yesteryear-actors-wore-for-their-wedding/photostory/100746642.cms?utm_source=newsletter&amp;utm_medium=email&amp;utm_campaign=Life_Style" style="color:#333; text-decoration:none;">What yesteryear actors wore for wedding</a></span><br><span style="display:block; height:50px; font:normal 17px/25px Arial; color:#333; overflow:hidden;">Looking for your wedding look inspiration for yesteryear Bollywood bea...</span><br><a href="http://timesofindia.indiatimes.com/newsletter/clicked/?cid=4558eb8b0b7c71cdc5da8b7d1f163656&amp;emailId=mitesh.salesmate@gmail.com&amp;url=https://timesofindia.indiatimes.com/life-style/fashion/web-stories/sharmila-tagore-to-jaya-bachchan-what-these-yesteryear-actors-wore-for-their-wedding/photostory/100746642.cms?utm_source=newsletter&amp;utm_medium=email&amp;utm_campaign=Life_Style" style="text-transform:uppercase;font-weight:700 !important; text-decoration:underline !important;font-weight:bold;margin-top: 7px; height:26px;  color:#000;  border-radius:3px; text-align:center; font:13px/26px &apos;Arial&apos;; text-decoration:none; display:inline-block; padding:0px 0px;">Web Stories<img style="max-width: 100%; float: right; margin-top: 5px; width: 8px; margin-left: 5px;" width="8" src="http://timesofindia.indiatimes.com/photo/66865007.cms"></a></td></tr></tbody></table></td></tr></tbody></table></td></tr><tr><td bgcolor="white" valign="top"><table border="0" cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td class="kr" height="30"></td></tr><tr><td height="155" valign="top" width="206"><a href="http://timesofindia.indiatimes.com/newsletter/clicked/?cid=4558eb8b0b7c71cdc5da8b7d1f163656&amp;emailId=mitesh.salesmate@gmail.com&amp;url=https://timesofindia.indiatimes.com/life-style/relationships/web-stories/why-do-people-still-cheat-in-happy-relationships/photostory/100709678.cms?utm_source=newsletter&amp;utm_medium=email&amp;utm_campaign=Life_Style"><img height="155" width="206" style="max-width: 100%; border-radius: 7px;" src="http://timesofindia.indiatimes.com/photo/100709678.cms"></a></td><td width="24"></td><td valign="top" width="380"><table border="0" cellpadding="0" cellspacing="0" width="380"><tbody><tr><td><span style="display:block; height:48px; font:bold 18px/25px Arial; text-transform:uppercase; overflow:hidden;"><a href="http://timesofindia.indiatimes.com/newsletter/clicked/?cid=4558eb8b0b7c71cdc5da8b7d1f163656&amp;emailId=mitesh.salesmate@gmail.com&amp;url=https://timesofindia.indiatimes.com/life-style/relationships/web-stories/why-do-people-still-cheat-in-happy-relationships/photostory/100709678.cms?utm_source=newsletter&amp;utm_medium=email&amp;utm_campaign=Life_Style" style="color:#333; text-decoration:none;">Why do people still cheat in happy relationships?</a></span><br><span style="display:block; height:50px; font:normal 17px/25px Arial; color:#333; overflow:hidden;">Some people tend to cheat on their partner even if they are pretty hap...</span><br><a href="http://timesofindia.indiatimes.com/newsletter/clicked/?cid=4558eb8b0b7c71cdc5da8b7d1f163656&amp;emailId=mitesh.salesmate@gmail.com&amp;url=https://timesofindia.indiatimes.com/life-style/relationships/web-stories/why-do-people-still-cheat-in-happy-relationships/photostory/100709678.cms?utm_source=newsletter&amp;utm_medium=email&amp;utm_campaign=Life_Style" style="text-transform:uppercase;font-weight:700 !important; text-decoration:underline !important;font-weight:bold;margin-top: 7px; height:26px;  color:#000;  border-radius:3px; text-align:center; font:13px/26px &apos;Arial&apos;; text-decoration:none; display:inline-block; padding:0px 0px;">Web stories<img style="max-width: 100%; float: right; margin-top: 5px; width: 8px; margin-left: 5px;" width="8" src="http://timesofindia.indiatimes.com/photo/66865007.cms"></a></td></tr></tbody></table></td></tr></tbody></table></td></tr><tr><td bgcolor="white" valign="top"><table border="0" cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td class="kr" height="30"></td></tr><tr><td height="155" valign="top" width="206"><a href="http://timesofindia.indiatimes.com/newsletter/clicked/?cid=4558eb8b0b7c71cdc5da8b7d1f163656&amp;emailId=mitesh.salesmate@gmail.com&amp;url=https://timesofindia.indiatimes.com/life-style/parenting/moments/umbilical-cord-why-should-parents-save-it/articleshow/100705423.cms?utm_source=newsletter&amp;utm_medium=email&amp;utm_campaign=Life_Style"><img height="155" width="206" style="max-width: 100%; border-radius: 7px;" src="http://timesofindia.indiatimes.com/photo/100705423.cms"></a></td><td width="24"></td><td valign="top" width="380"><table border="0" cellpadding="0" cellspacing="0" width="380"><tbody><tr><td><span style="display:block; height:48px; font:bold 18px/25px Arial; text-transform:uppercase; overflow:hidden;"><a href="http://timesofindia.indiatimes.com/newsletter/clicked/?cid=4558eb8b0b7c71cdc5da8b7d1f163656&amp;emailId=mitesh.salesmate@gmail.com&amp;url=https://timesofindia.indiatimes.com/life-style/parenting/moments/umbilical-cord-why-should-parents-save-it/articleshow/100705423.cms?utm_source=newsletter&amp;utm_medium=email&amp;utm_campaign=Life_Style" style="color:#333; text-decoration:none;">Umbilical cord: Why should parents save it?</a></span><br><span style="display:block; height:50px; font:normal 17px/25px Arial; color:#333; overflow:hidden;">The stem cells present in umbilical cord has immense medical potential...</span><br><a href="http://timesofindia.indiatimes.com/newsletter/clicked/?cid=4558eb8b0b7c71cdc5da8b7d1f163656&amp;emailId=mitesh.salesmate@gmail.com&amp;url=https://timesofindia.indiatimes.com/life-style/parenting/moments/umbilical-cord-why-should-parents-save-it/articleshow/100705423.cms?utm_source=newsletter&amp;utm_medium=email&amp;utm_campaign=Life_Style" style="text-transform:uppercase;font-weight:700 !important; text-decoration:underline !important;font-weight:bold;margin-top: 7px; height:26px;  color:#000;  border-radius:3px; text-align:center; font:13px/26px &apos;Arial&apos;; text-decoration:none; display:inline-block; padding:0px 0px;">Moments<img style="max-width: 100%; float: right; margin-top: 5px; width: 8px; margin-left: 5px;" width="8" src="http://timesofindia.indiatimes.com/photo/66865007.cms"></a></td></tr></tbody></table></td></tr></tbody></table></td></tr><tr><td bgcolor="white" height="20"><img width="10" height="10" align="top" src="http://timesofindia.indiatimes.com/photo/14690948.cms" style="max-width: 100%;"></td></tr><tr><td><a href="http://timesofindia.indiatimes.com/newsletter/clicked/?cid=4558eb8b0b7c71cdc5da8b7d1f163656&amp;emailId=mitesh.salesmate@gmail.com&amp;url=https://timesofindia.indiatimes.com/life-style/relationships/love-sex/zodiac-signs-who-are-very-confident-during-entrance-exams/photostory/100710525.cms?utm_source=newsletter&amp;utm_medium=email&amp;utm_campaign=Life_Style" style="color:#333; text-decoration:none;"><img height="315" width="610" style="max-width: 100%; border-radius: 7px;" src="http://timesofindia.indiatimes.com/thumb/msid-100710525,width-610,height-315.cms"></a></td></tr><tr><td style="font:bold 20px/40px Arial;"><a href="http://timesofindia.indiatimes.com/newsletter/clicked/?cid=4558eb8b0b7c71cdc5da8b7d1f163656&amp;emailId=mitesh.salesmate@gmail.com&amp;url=https://timesofindia.indiatimes.com/life-style/relationships/love-sex/zodiac-signs-who-are-very-confident-during-entrance-exams/photostory/100710525.cms?utm_source=newsletter&amp;utm_medium=email&amp;utm_campaign=Life_Style" style="color:#333; text-decoration:none;">These zodiacs are very confident during entrance exams</a></td></tr><tr><td style="font:normal 17px/25px Arial; color:#333;"><span style="display:block; height:50px; font:normal 17px/25px Arial; color:#333; overflow:hidden;">Curious to know if your zodiac sign is one of the confident ones during entrance exams? Read this li...</span></td></tr><tr><td bgcolor="white" height="20"><img width="10" height="10" align="top" src="http://timesofindia.indiatimes.com/photo/14690948.cms" style="max-width: 100%;"></td></tr><tr><td bgcolor="white" valign="top"><table border="0" cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td class="kr" height="30"></td></tr><tr><td height="155" valign="top" width="206"><a href="http://timesofindia.indiatimes.com/newsletter/clicked/?cid=4558eb8b0b7c71cdc5da8b7d1f163656&amp;emailId=mitesh.salesmate@gmail.com&amp;url=https://timesofindia.indiatimes.com/life-style/health-fitness/web-stories/how-aloo-ka-paratha-lover-vicky-kaushal-stays-lean/photostory/100735046.cms?utm_source=newsletter&amp;utm_medium=email&amp;utm_campaign=Life_Style"><img height="155" width="206" style="max-width: 100%; border-radius: 7px;" src="http://timesofindia.indiatimes.com/photo/100735046.cms"></a></td><td width="24"></td><td valign="top" width="380"><table border="0" cellpadding="0" cellspacing="0" width="380"><tbody><tr><td><span style="display:block; height:48px; font:bold 18px/25px Arial; text-transform:uppercase; overflow:hidden;"><a href="http://timesofindia.indiatimes.com/newsletter/clicked/?cid=4558eb8b0b7c71cdc5da8b7d1f163656&amp;emailId=mitesh.salesmate@gmail.com&amp;url=https://timesofindia.indiatimes.com/life-style/health-fitness/web-stories/how-aloo-ka-paratha-lover-vicky-kaushal-stays-lean/photostory/100735046.cms?utm_source=newsletter&amp;utm_medium=email&amp;utm_campaign=Life_Style" style="color:#333; text-decoration:none;">Paratha lover Vicky Kaushal stays lean</a></span><br><span style="display:block; height:50px; font:normal 17px/25px Arial; color:#333; overflow:hidden;">Vicky Kaushal spends a lot of time working out to maintain his muscles...</span><br><a href="http://timesofindia.indiatimes.com/newsletter/clicked/?cid=4558eb8b0b7c71cdc5da8b7d1f163656&amp;emailId=mitesh.salesmate@gmail.com&amp;url=https://timesofindia.indiatimes.com/life-style/health-fitness/web-stories/how-aloo-ka-paratha-lover-vicky-kaushal-stays-lean/photostory/100735046.cms?utm_source=newsletter&amp;utm_medium=email&amp;utm_campaign=Life_Style" style="text-transform:uppercase;font-weight:700 !important; text-decoration:underline !important;font-weight:bold;margin-top: 7px; height:26px;  color:#000;  border-radius:3px; text-align:center; font:13px/26px &apos;Arial&apos;; text-decoration:none; display:inline-block; padding:0px 0px;">Web stories<img style="max-width: 100%; float: right; margin-top: 5px; width: 8px; margin-left: 5px;" width="8" src="http://timesofindia.indiatimes.com/photo/66865007.cms"></a></td></tr></tbody></table></td></tr></tbody></table></td></tr><tr><td bgcolor="white" valign="top"><table border="0" cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td class="kr" height="30"></td></tr><tr><td height="155" valign="top" width="206"><a href="http://timesofindia.indiatimes.com/newsletter/clicked/?cid=4558eb8b0b7c71cdc5da8b7d1f163656&amp;emailId=mitesh.salesmate@gmail.com&amp;url=https://timesofindia.indiatimes.com/life-style/books/features/8-must-read-books-on-psychology-and-the-human-mind/photostory/100738793.cms?utm_source=newsletter&amp;utm_medium=email&amp;utm_campaign=Life_Style"><img height="155" width="206" style="max-width: 100%; border-radius: 7px;" src="http://timesofindia.indiatimes.com/photo/100738793.cms"></a></td><td width="24"></td><td valign="top" width="380"><table border="0" cellpadding="0" cellspacing="0" width="380"><tbody><tr><td><span style="display:block; height:48px; font:bold 18px/25px Arial; text-transform:uppercase; overflow:hidden;"><a href="http://timesofindia.indiatimes.com/newsletter/clicked/?cid=4558eb8b0b7c71cdc5da8b7d1f163656&amp;emailId=mitesh.salesmate@gmail.com&amp;url=https://timesofindia.indiatimes.com/life-style/books/features/8-must-read-books-on-psychology-and-the-human-mind/photostory/100738793.cms?utm_source=newsletter&amp;utm_medium=email&amp;utm_campaign=Life_Style" style="color:#333; text-decoration:none;">8 must-read books on psychology and human mind</a></span><br><span style="display:block; height:50px; font:normal 17px/25px Arial; color:#333; overflow:hidden;">Exploring the realms of psychology and the human mind is a fascinating...</span><br><a href="http://timesofindia.indiatimes.com/newsletter/clicked/?cid=4558eb8b0b7c71cdc5da8b7d1f163656&amp;emailId=mitesh.salesmate@gmail.com&amp;url=https://timesofindia.indiatimes.com/life-style/books/features/8-must-read-books-on-psychology-and-the-human-mind/photostory/100738793.cms?utm_source=newsletter&amp;utm_medium=email&amp;utm_campaign=Life_Style" style="text-transform:uppercase;font-weight:700 !important; text-decoration:underline !important;font-weight:bold;margin-top: 7px; height:26px;  color:#000;  border-radius:3px; text-align:center; font:13px/26px &apos;Arial&apos;; text-decoration:none; display:inline-block; padding:0px 0px;">Features<img style="max-width: 100%; float: right; margin-top: 5px; width: 8px; margin-left: 5px;" width="8" src="http://timesofindia.indiatimes.com/photo/66865007.cms"></a></td></tr></tbody></table></td></tr></tbody></table></td></tr><tr><td bgcolor="white" valign="top"><table border="0" cellpadding="0" cellspacing="0" width="100%"><tbody><tr><td class="kr" height="30"></td></tr><tr><td height="155" valign="top" width="206"><a href="http://timesofindia.indiatimes.com/newsletter/clicked/?cid=4558eb8b0b7c71cdc5da8b7d1f163656&amp;emailId=mitesh.salesmate@gmail.com&amp;url=https://timesofindia.indiatimes.com/life-style/health-fitness/health-news/scad-this-heart-attack-affects-young-women-mostly-medically-validated-facts-to-know/photostory/100702131.cms?utm_source=newsletter&amp;utm_medium=email&amp;utm_campaign=Life_Style"><img height="155" width="206" style="max-width: 100%; border-radius: 7px;" src="http://timesofindia.indiatimes.com/photo/100702131.cms"></a></td><td width="24"></td><td valign="top" width="380"><table border="0" cellpadding="0" cellspacing="0" width="380"><tbody><tr><td><span style="display:block; height:48px; font:bold 18px/25px Arial; text-transform:uppercase; overflow:hidden;"><a href="http://timesofindia.indiatimes.com/newsletter/clicked/?cid=4558eb8b0b7c71cdc5da8b7d1f163656&amp;emailId=mitesh.salesmate@gmail.com&amp;url=https://timesofindia.indiatimes.com/life-style/health-fitness/health-news/scad-this-heart-attack-affects-young-women-mostly-medically-validated-facts-to-know/photostory/100702131.cms?utm_source=newsletter&amp;utm_medium=email&amp;utm_campaign=Life_Style" style="color:#333; text-decoration:none;">SCAD, an uncommon heart attack in women</a></span><br><span style="display:block; height:50px; font:normal 17px/25px Arial; color:#333; overflow:hidden;">An uncommon form of heart attack, called SCAD, is known to affect you...</span><br><a href="http://timesofindia.indiatimes.com/newsletter/clicked/?cid=4558eb8b0b7c71cdc5da8b7d1f163656&amp;emailId=mitesh.salesmate@gmail.com&amp;url=https://timesofindia.indiatimes.com/life-style/health-fitness/health-news/scad-this-heart-attack-affects-young-women-mostly-medically-validated-facts-to-know/photostory/100702131.cms?utm_source=newsletter&amp;utm_medium=email&amp;utm_campaign=Life_Style" style="text-transform:uppercase;font-weight:700 !important; text-decoration:underline !important;font-weight:bold;margin-top: 7px; height:26px;  color:#000;  border-radius:3px; text-align:center; font:13px/26px &apos;Arial&apos;; text-decoration:none; display:inline-block; padding:0px 0px;">Health News<img style="max-width: 100%; float: right; margin-top: 5px; width: 8px; margin-left: 5px;" width="8" src="http://timesofindia.indiatimes.com/photo/66865007.cms"></a></td></tr></tbody></table></td></tr></tbody></table></td></tr><tr><td class="kr" height="50"><hr style="width:100%; border:1px solid #e5e5e5;"></td></tr></tbody></table></td></tr><tr><td align="center"><table border="0" cellpadding="5" cellspacing="5"><tbody><tr><td><a href="https://www.facebook.com/toilifestyle/"><img alt src="http://timesofindia.indiatimes.com/photo/66604156.cms" style="max-width: 100%;"></a></td><td><a href="https://twitter.com/TOILifestyle"><img alt src="http://timesofindia.indiatimes.com/photo/66604178.cms" style="max-width: 100%;"></a></td><td><a href="mailto:lifestyle.toi@gmail.com?Subject= ETimes LifeStyle Newsletter - Today&apos;s Highlights: Heart attack risk rises on Mondays: Study" target="_top"><img alt src="http://timesofindia.indiatimes.com/photo/66604211.cms" style="max-width: 100%;"></a></td></tr></tbody></table></td></tr><tr><td bgcolor="white" height="10"><img width="10" height="10" align="top" src="http://timesofindia.indiatimes.com/photo/14690948.cms" style="max-width: 100%;"></td></tr><tr><td align="center" style="color:#1c1c1c; font-size:13px; font-weight:bold;"><a href="http://timesofindia.indiatimes.com/unsubscribe/newsletterhome.cms?email=mitesh.salesmate@gmail.com&amp;nlid=1004" style="color:#1c1c1c; text-transform:uppercase; padding:0 20px; text-decoration:none;">Unsubscribe</a> <a href="https://timesofindia.indiatimes.com/privacy-policy/cookiepolicy/86934312.cms" style="color:#1c1c1c; text-transform:uppercase; padding:0 20px; text-decoration:none;">Privacy Policy</a> <a href="https://www.indiatimes.com/termsandcondition/" style="color:#1c1c1c; text-transform:uppercase; padding:0 20px; text-decoration:none;">Terms of Use</a></td></tr><tr><td bgcolor="white" height="30"><img width="10" height="30" align="top" src="http://timesofindia.indiatimes.com/photo/14690948.cms" style="max-width: 100%;"></td></tr></tbody></table></td></tr></tbody></table><img style="max-width: 100%; height: 0px; width: 0px;" src="http://timesofindia.indiatimes.com/newsletter/pixel/?code=4558eb8b0b7c71cdc5da8b7d1f163656" width="0" height="0">`

**Comment by the-airbender** [comment]
Hello @VishaliOSRapidops,

To set the html content to the editor There are two options, use `controller.setText` or pasting the text copied from the html page instead of html code. In the above scenario, you are trying to paste the html code, the editor will consider it as a code and shows the same text. 
 
I suggest you to use the `controller.setText` method to set the text.  I hope this input proves helpful. Feel free to reopen this issue if you still face any challenges.

Thanks :)
