### ISSUE TITLE
[BUG] Links get changed to "about:blank" without having touched them

### ISSUE THREAD

**Issue by madlick71** [the-airbender/quill_html_editor#97]
This is the original HTML which I put into the Quill Editor via the controller.setText() method:
`<p>Test with a <a href="/ticket/202303871" rel="noopener noreferrer" target="_blank">Link</a></p>`

And this is the same HTML after retrieving it via the controller.getText() method:
`<p>Test with a <a href="about:blank" rel="noopener noreferrer" target="_blank">Link</a></p>`

I didn't edit anything, I didn't even touch the Editor. 

Thanks in advance  :)
Stefan

**Comment by the-airbender** [comment]
Hello @madlick71 

This issue has been resolved in the new release. Please check it out and share your feedback.

Thanks :)

**Comment by madlick71** [comment]
Hi @the-airbender 

this works perfectly now! Thank you for the quick work and response 👍

**Comment by wrteam02** [comment]
i am using latest version:  quill_html_editor: ^2.2.7
facing link click issue

<a href="www.google.com" rel="noopener noreferrer" target="_blank">Test</a>

link converted in noreferrer and while on preview mode trying to click on link preview no more working appear blank screen
