### ISSUE TITLE
Copy and paste HTML[BUG]

### ISSUE THREAD

**Issue by AvoMandjian** [the-airbender/quill_html_editor#99]
**Describe the bug**
when I copy an HTML string, let's say the below

`<p>Welcome <a href='@1'>@Avo</a> to our <a href='#dp-flutter-widgets'>#dp-flutter-widgets</a></p>
`
pasting the above directly into the editor won't format it, but using quillEditorController.setText method it pastes it formatted

**To Reproduce**
1. copy `<p>Welcome <a href='@1'>@Avo</a> to our <a href='#dp-flutter-widgets'>#dp-flutter-widgets</a></p>
`
2. click inside the editor, right click->paste

**Expected behavior**
it should paste it formatted and not as a normal string

**Screenshots**
Expected behavior (achieved by using `quillEditorController.setText(<p>Welcome <a href='@1'>@Avo</a> to our <a href='#dp-flutter-widgets'>#dp-flutter-widgets</a></p>)`)
<img width="871" alt="Screenshot 2023-07-19 at 9 45 11 PM" src="https://github.com/the-airbender/quill_html_editor/assets/59996570/c73e05e7-e1a0-4191-9ff8-68d4db91167c">

Actual behavior
<img width="865" alt="Screenshot 2023-07-19 at 9 44 56 PM" src="https://github.com/the-airbender/quill_html_editor/assets/59996570/23b86817-ced7-4718-9e60-ac9c0e44ab0f">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome

**Smartphone (please complete the following information):**
 - Version 114.0.5735.198

**Flutter Doctor**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64, locale en-LB)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.80.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

**Additional context**
No additional context

**Comment by the-airbender** [comment]
Hello @AvoMandjian,

Sorry for the late response.
This is the default behaviour of the QuillJS editor, if we paste any html text, it will consider it a a code block and shows the pasted content. 
Closing this issue for now. However, I will also see if there is be any workaround for this.

Thanks :)
